import {officialLogo} from './branding';
import {RoverCameras} from './RoverCameras';
import {drawCameraOverlay} from './camera-overlay';
import {drawSoilOverlay} from './video-overlays';
import {SoilPanel} from './SoilPanel';
import {SensorPanel} from './SensorPanel';
import {useEffect,useRef,useState,useCallback} from 'react';
import * as echarts from 'echarts/core';
import {BarChart,LineChart} from 'echarts/charts';
import {GridComponent,TooltipComponent} from 'echarts/components';
import {CanvasRenderer} from 'echarts/renderers';
import {MaintenancePanel} from './MaintenancePanel';
import {AnalysisPanel} from './analysis';
import {FieldScene,type SceneOptions} from './scene';
import {DURATION,bayCycle,stationCycle,chapters,missionAt,phaseIndex,statistics,cells,GRID,colorFor,telemetryUntil,csvReport,clamp,type ViewMode,type CameraMode} from './mission';
echarts.use([BarChart,LineChart,GridComponent,TooltipComponent,CanvasRenderer]);
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
const formatTime=(n:number)=>`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function Chart({kind,time}:{kind:'distribution'|'telemetry';time:number}){const el=useRef<HTMLDivElement>(null),chart=useRef<echarts.ECharts|null>(null);useEffect(()=>{if(!el.current)return;const c=echarts.init(el.current);chart.current=c;const ro=new ResizeObserver(()=>c.resize());ro.observe(el.current);return()=>{ro.disconnect();c.dispose();chart.current=null}},[]);useEffect(()=>{const common={animation:false,textStyle:{fontFamily:'Arial',color:'#9bb0ba'},grid:{top:18,left:39,right:12,bottom:25},tooltip:{trigger:'axis',backgroundColor:'#14262f',borderColor:'#415460',textStyle:{color:'#fff'}},yAxis:{type:'value',axisLabel:{fontSize:11},splitLine:{lineStyle:{color:'#263a45'}}}};if(kind==='distribution')chart.current?.setOption({...common,xAxis:{type:'category',data:statistics.bins.map(b=>b.min.toFixed(1)),axisLabel:{fontSize:10},axisTick:{show:false},axisLine:{lineStyle:{color:'#39505b'}}},series:[{name:'Celdas',type:'bar',data:statistics.bins.map(b=>({value:b.count,itemStyle:{color:`rgb(${colorFor((b.min+b.max)/2).join(',')})`}})),barWidth:'65%',itemStyle:{borderRadius:[2,2,0,0]}}]},true);else {const data=telemetryUntil(time);chart.current?.setOption({...common,yAxis:{...common.yAxis,min:0,max:100,axisLabel:{fontSize:11,formatter:'{value}%'}},xAxis:{type:'value',min:0,max:DURATION,axisLabel:{fontSize:11,formatter:'{value}s'},splitLine:{show:false},axisLine:{lineStyle:{color:'#39505b'}}},series:[{name:'Batería aérea',type:'line',data:data.map(r=>[r[0],r[1]]),showSymbol:false,lineStyle:{color:'#55bdfa',width:2},itemStyle:{color:'#55bdfa'}},{name:'Cobertura',type:'line',data:data.map(r=>[r[0],r[3]]),showSymbol:false,lineStyle:{color:'#80d6a3',width:2},itemStyle:{color:'#80d6a3'},areaStyle:{color:'rgba(128,214,163,.06)'}}]},true)}},[kind,Math.floor(time)]);return <div ref={el} className="chart" role="img" aria-label={kind==='distribution'?`Distribución de ${statistics.count} celdas sintéticas. NDVI medio ${statistics.mean.toFixed(2)}.`:`Batería y cobertura simuladas hasta ${Math.floor(time)} segundos.`}/>}
function FieldMap({selected,onSelect}:{selected:number;onSelect:(i:number)=>void}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx)return;for(const c of cells){ctx.fillStyle=`rgb(${colorFor(c.value).join(',')})`;ctx.fillRect(c.col*5,c.row*5,5,5)}const c=cells[selected];ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(c.col*5-2,c.row*5-2,9,9)},[selected]);return <canvas ref={ref} width={300} height={210} className="field-map" tabIndex={0} role="grid" aria-label={`Mapa NDVI simulado. Celda ${selected+1}, valor ${cells[selected].value.toFixed(3)}. Usa las flechas para explorar.`} onKeyDown={e=>{const delta=({ArrowRight:1,ArrowLeft:-1,ArrowUp:-GRID.cols,ArrowDown:GRID.cols} as Record<string,number>)[e.key];if(delta){e.preventDefault();onSelect(clamp(selected+delta,0,cells.length-1))}}} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();const col=Math.min(GRID.cols-1,Math.floor((e.clientX-r.left)/r.width*GRID.cols)),row=Math.min(GRID.rows-1,Math.floor((e.clientY-r.top)/r.height*GRID.rows));onSelect(row*GRID.cols+col)}}/>}
export function FieldCinema(){
 const [presenting,setPresenting]=useState(true),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[view,setView]=useState<ViewMode>('mission'),[camera,setCamera]=useState<CameraMode>('auto'),[ndvi,setNdvi]=useState(true),[quality,setQuality]=useState<'high'|'balanced'>('high'),[selected,setSelected]=useState(1308),[ready,setReady]=useState(false),[error,setError]=useState(''),[deployment,setDeployment]=useState(1),[probe,setProbe]=useState(0),[bay,setBay]=useState(0),[explode,setExplode]=useState(false),[recording,setRecording]=useState(false),[notice,setNotice]=useState(''),[inspection,setInspection]=useState(0),[cyclePlaying,setCyclePlaying]=useState(false),[analysis,setAnalysis]=useState(false),[rgb,setRgb]=useState(''),[thermal,setThermal]=useState(false);
 const stage=useRef<HTMLDivElement>(null),scene=useRef<FieldScene|null>(null),timeRef=useRef(time),root=useRef<HTMLDivElement>(null),recordStop=useRef<(()=>void)|null>(null);
 const productCycle=view==='sentinel'?stationCycle(inspection):bayCycle(inspection);
 const options:SceneOptions={time,view,camera,ndvi,quality,deployment,probe,bay,inspection,thermal,explode,selected};timeRef.current=time;const m=missionAt(time),chapter=chapters[m.phase];
 useEffect(()=>{if(!stage.current)return;let world:FieldScene;try{world=new FieldScene(stage.current,options,setSelected,()=>setReady(true),setError);scene.current=world}catch{setError('Este dispositivo no puede iniciar la vista 3D. Puedes explorar el mapa y los gráficos.');return}return()=>{recordStop.current?.();world.dispose();scene.current=null}},[]);
 useEffect(()=>scene.current?.update(options),[time,view,camera,ndvi,quality,deployment,probe,bay,inspection,thermal,explode,selected]);
 useEffect(()=>{if(!playing)return;let id=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.1);last=now;setTime(t=>{const next=Math.min(DURATION,t+dt*speed);return next});id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[playing,speed]);
 useEffect(()=>setThermal(time>=94),[time>=94]);
 useEffect(()=>{if(time>=DURATION)setPlaying(false)},[time]);
 const play=useCallback(()=>{if(recordStop.current)return;setView('mission');if(timeRef.current>=DURATION)setTime(0);setPlaying(p=>!p)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,button,a,textarea,[role="grid"]'))return;if(e.code==='Space'){e.preventDefault();play()}if(e.key==='Escape')recordStop.current?.();if(e.key.toLowerCase()==='r'&&!recordStop.current){setTime(0);setPlaying(false);scene.current?.resetCamera()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[play]);
 useEffect(()=>{if(!cyclePlaying)return;let id=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.1);last=now;setInspection(v=>Math.min(1,v+dt/24));id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[cyclePlaying]);
 useEffect(()=>{if(inspection>=1)setCyclePlaying(false)},[inspection]);
 async function openAnalysis(){if(recordStop.current)return;setPlaying(false);setRgb(scene.current?.aerialSnapshot()??'');setAnalysis(true)}
 function changeView(v:ViewMode){if(recordStop.current)return;setCyclePlaying(false);setInspection(0);setBay(0);setView(v);setPlaying(false);scene.current?.resetCamera()}
 async function capture(){const image=await scene.current?.screenshot();if(image)download(image,'UPAIDOWN-concepto-3D.png')}
 async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await root.current?.requestFullscreen()}catch{setNotice('La pantalla completa no está disponible en este navegador.')}}
 async function startRecording(){if(!scene.current||!ready||typeof MediaRecorder==='undefined'){setNotice('La grabación no está disponible en este navegador.');return}const logo=new Image();logo.src=officialLogo;await logo.decode();if(!scene.current)return;const live=scene.current.canvas();const canvas=document.createElement('canvas');canvas.width=1600;canvas.height=900;const ctx=canvas.getContext('2d')!;const mediaType=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mediaType){setNotice('Este navegador no permite grabar vídeo. Puedes ver los avances en la web corporativa.');return}setView('mission');setCamera('auto');setAnalysis(false);setCyclePlaying(false);setThermal(false);scene.current.resetCamera();setTime(0);timeRef.current=0;setSpeed(1);setPlaying(true);setRecording(true);setNotice('Grabando la misión completa. El vídeo se descargará al terminar.');const stream=canvas.captureStream(30);let recorder:MediaRecorder;try{recorder=new MediaRecorder(stream,{mimeType:mediaType,videoBitsPerSecond:8_000_000})}catch{stream.getTracks().forEach(t=>t.stop());setRecording(false);setNotice('No se ha podido iniciar la grabación.');return}const chunks:Blob[]=[];let raf=0,stopped=false,failed=false;const stop=()=>{if(stopped)return;stopped=true;cancelAnimationFrame(raf);if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());setRecording(false);setPlaying(false);recordStop.current=null};recordStop.current=stop;recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onerror=()=>{failed=true;stop();setNotice('La grabación se interrumpió.')};recorder.onstop=()=>{if(chunks.length&&!failed){download(new Blob(chunks,{type:mediaType}),`UPAIDOWN-mision-3D.${mediaType.startsWith('video/mp4')?'mp4':'webm'}`);setNotice(timeRef.current>=DURATION?'Misión completa guardada. Puede reproducirse sin conexión.':'Fragmento guardado. Puede reproducirse sin conexión.')}};
 const frame=()=>{const t=timeRef.current,s=missionAt(t),c=chapters[s.phase];ctx.fillStyle='#0b151d';ctx.fillRect(0,0,1600,900);const ratio=Math.min(1600/live.width,900/live.height),w=live.width*ratio,h=live.height*ratio;ctx.drawImage(live,(1600-w)/2,(900-h)/2,w,h);const grad=ctx.createLinearGradient(0,570,0,900);grad.addColorStop(0,'transparent');grad.addColorStop(1,'rgba(5,15,21,.94)');ctx.fillStyle=grad;ctx.fillRect(0,570,1600,330);ctx.fillStyle='#eff5f1';ctx.fillRect(32,22,282,66);ctx.drawImage(logo,48,36,250,250*logo.height/logo.width);ctx.fillStyle='#fff';ctx.font='bold 20px Arial';ctx.fillText('FIELD CINEMA',336,60);ctx.font='18px Arial';ctx.fillText('CONCEPTO 3D · DATOS SIMULADOS',1160,53);ctx.font='bold 43px Arial';ctx.fillText(c.title,48,755);ctx.font='23px Arial';ctx.fillStyle='#d4e0e4';ctx.fillText(c.body,48,800,1450);ctx.fillStyle='#30424b';ctx.fillRect(48,848,1504,4);ctx.fillStyle='#7cd7ac';ctx.fillRect(48,848,1504*t/DURATION,4);ctx.font='18px Arial';ctx.fillText(`${formatTime(t)} / 3:12    COBERTURA ${Math.round(s.coverage*100)}%    ${s.sample?'MUESTRA DE SUELO REGISTRADA':'MISIÓN EN CURSO'}`,48,882);if(s.ndvi){for(const cell of cells){ctx.fillStyle=`rgb(${colorFor(cell.value).join(',')})`;ctx.fillRect(1260+cell.col*4,95+cell.row*4,4,4)}ctx.fillStyle='#10202b';ctx.fillRect(1260,263,240,40);ctx.fillStyle='#fff';ctx.font='17px Arial';ctx.fillText(`NDVI medio ${statistics.mean.toFixed(2)}`,1270,289)}if(scene.current)drawCameraOverlay(ctx,t,scene.current);drawSoilOverlay(ctx,t);if(t>=DURATION){stop();return}raf=requestAnimationFrame(frame)};await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));if(!stopped){recorder.start(1000);frame()}}
 return <div className={`cinema-app ${presenting?'presentation-mode':''} ${view!=='mission'?'product-mode':''}`} ref={root}>
 <header className="cinema-header"><a className="brand" href="https://upaidown.com" aria-label="UPAIDOWN, web corporativa"><img src={`${import.meta.env.BASE_URL}brand/upaidown-official.png`} alt="upAIdown" width="180" height="39"/></a><span className="edition">FIELD CINEMA <i/> 01</span><div className="header-actions"><button className="presentation-switch" aria-pressed={presenting} onClick={()=>setPresenting(p=>!p)}>{presenting?'Mostrar datos':'Modo presentación'}</button><span className="simulation-tag"><i/> Demostración simulada</span><button onClick={fullscreen} title="Pantalla completa" aria-label="Pantalla completa">⛶</button></div></header>
 <main className="cinema-main"><section className={`experience ${view==='mission'&&m.sampling?'sampling-view':''}`}  aria-label="Experiencia tridimensional">
 <div className="scene-toolbar"><fieldset disabled={recording} className="view-tabs" aria-label="Vista"><button className={view==='mission'?'active':''} onClick={()=>changeView('mission')}>Misión</button><button className={view==='rover'?'active':''} onClick={()=>changeView('rover')}>WALL‑AI</button><button className={view==='sentinel'?'active':''} onClick={()=>changeView('sentinel')}>Station</button></fieldset><label className="quality-label">Calidad <select value={quality} onChange={e=>setQuality(e.target.value as 'high'|'balanced')}><option value="high">Alta</option><option value="balanced">Equilibrada</option></select></label></div>
 <div ref={stage} className="scene-stage"/>
 {!ready&&!error&&<div className="scene-loading"><span className="loading-ring"/><strong>Preparando el campo</strong><p>Cargando los equipos y la luz del entorno.</p></div>}
 {error&&<div className="scene-error"><strong>Vista de datos disponible</strong><p>{error}</p><button onClick={()=>location.reload()}>Recargar 3D</button></div>}
 <div className="scene-topline"><span>{view==='mission'?'PARCELA DE DEMOSTRACIÓN / VIÑEDO':'EXPLORADOR DE PRODUCTO'}</span><span className="live-state">{view!=='mission'?(cyclePlaying?'CICLO EN CURSO':'CONTROL MANUAL'):playing?'REPRODUCIENDO':time===DURATION?'MISIÓN COMPLETA':'EN PAUSA'}</span></div>
 {view==='mission'?<><div className="scene-caption"><span className="chapter-kicker">{String(m.phase+1).padStart(2,'0')} / OBSERVA · INSPECCIONA · CONECTA · DECIDE</span><h1>{chapter.title}</h1><p>{chapter.body}</p></div><div className="camera-controls" aria-label="Cámara"><span>CÁMARA</span>{([['auto','Guiada'],['overview','General'],['drone','Aérea'],['rover','WALL‑AI'],['sentinel','Station'],['anomaly','Parcela'],['local','Dron WALL-AI'],['aircraft','Dron · detalle'],['probe','Sonda'],['sensors','Cámaras']] as const).map(([key,label])=><button key={key} className={camera===key?'active':''} onClick={()=>{setCamera(key);scene.current?.resetCamera()}}>{label}</button>)}</div></>:<><div className="scene-caption product-caption"><span className="chapter-kicker">EXPLORADOR DE PRODUCTO / CONCEPTO 3D</span><h1>{view==='rover'?'WALL‑AI':'UPAIDOWN Station'}</h1><p>{view==='rover'?'Inspección terrestre y aérea. Bahía articulada, dron embarcado y sonda de suelo.':'Presencia fija. Mástil, sensores ambientales y cajón con elevador de tijera.'}</p></div><div className="product-controls">{view==='sentinel'&&<label>Despliegue del mástil<input aria-label="Despliegue del mástil" type="range" min="0" max="1" step=".01" value={deployment} onChange={e=>setDeployment(+e.target.value)}/></label>}<label>Apertura de bahía<input aria-label="Apertura de bahía" type="range" min="0" max="1" step=".01" value={inspection?(productCycle.door+productCycle.platform)/2:bay} onChange={e=>{setInspection(0);setCyclePlaying(false);setBay(+e.target.value)}}/></label>{view==='rover'&&<><label>Sonda de suelo<input aria-label="Sonda de suelo" type="range" min="0" max="1" step=".01" value={probe} onChange={e=>setProbe(+e.target.value)}/></label><label className="checkbox-control"><input type="checkbox" checked={explode} onChange={e=>setExplode(e.target.checked)}/> Separar orugas</label></>}<p className="bay-status">{inspection?productCycle.status:bay===0?"Dron alojado":bay===1?"Plataforma preparada":"Apertura secuenciada"}</p><label>Ciclo de salida y retorno<input aria-label="Ciclo del dron" type="range" min="0" max="1" step=".005" value={inspection} onChange={e=>{setCyclePlaying(false);setInspection(+e.target.value)}}/></label><button onClick={()=>{setInspection(0);setCyclePlaying(true)}}>Reproducir ciclo del dron</button><button onClick={()=>scene.current?.resetCamera()}>Restablecer cámara</button></div></>}
 {presenting&&view==='mission'&&!m.sampling&&time>=33&&time<192&&<div className="presentation-evidence">{time<72||m.roverBay.air>0?<SensorPanel time={time} playing={playing} scene={ready?scene.current:null}/>:<RoverCameras time={time} playing={playing} scene={ready?scene.current:null}/>}</div>}<div className="thermal-toggle">{view==='mission'&&!presenting&&time>=94&&<><button onClick={()=>{setPresenting(false);setThermal(true);setCamera('local');document.querySelector('.maintenance')?.scrollIntoView({block:'nearest',behavior:'smooth'})}}>3 avisos · mantenimiento ↗</button><label><input type="checkbox" checked={thermal} onChange={e=>setThermal(e.target.checked)}/> Térmica local · simulada</label></>}</div>{view==='mission'&&m.sampling&&<div className="soil-stage"><SoilPanel time={time} compact/></div>}{view==='mission'&&presenting&&m.report&&<button className="presentation-report" disabled={recording} onClick={openAnalysis}>Abrir informe de la misión ↗</button>}<div className="scene-footnote">Arrastra para girar · Rueda para acercar <span>Modelos conceptuales; dimensiones no validadas.</span></div>
 </section>
 {!presenting&&view==='mission'&&<aside className="data-rail"><fieldset className="rail-interactions" disabled={recording}><div className="rail-title"><div><span>LECTURA DE MISIÓN</span><h2>Del campo al dato<span>.</span></h2></div><span className="run-code">M‑001</span></div>
 <div className="inspection-shortcuts"><button onClick={()=>{setView('mission');setTime(72);setCamera('auto');setPlaying(true);scene.current?.resetCamera()}}>▶ Ver desplazamiento</button><button onClick={()=>{setView('mission');setTime(94);setCamera('auto');setPlaying(true);scene.current?.resetCamera()}}>▶ Ver toma de suelo</button><button onClick={()=>{setView('mission');setTime(86);setCamera('sensors');setPlaying(false);scene.current?.resetCamera()}}>Ver cámaras y sensores</button></div>
 {view==='mission'&&time>=72&&<RoverCameras time={time} playing={playing} scene={ready?scene.current:null}/>}<SensorPanel time={time} playing={playing} scene={ready?scene.current:null}/><div className="metrics"><div><span>Cobertura</span><strong>{Math.round(m.coverage*100)}<small>%</small></strong><div className="progress"><i style={{width:`${m.coverage*100}%`}}/></div></div><div><span>NDVI medio</span><strong>{m.ndvi?statistics.mean.toFixed(2):'—'}</strong><small>{m.ndvi?`${statistics.count.toLocaleString('es')} celdas`:'Pendiente de captura'}</small></div></div>
 <div className="rail-section"><div className="section-heading"><h3>NDVI · parcela completa</h3><label><input type="checkbox" checked={ndvi} onChange={e=>setNdvi(e.target.checked)}/> Capa 3D</label></div>{m.ndvi?<><FieldMap selected={selected} onSelect={setSelected}/><div className="color-scale"><span>−1</span><i/><span>+1</span></div><div className="cell-reading"><span>Celda {cells[selected].col+1}:{cells[selected].row+1}</span><b>NDVI {cells[selected].value.toFixed(3)} · {cells[selected].canopy?"dosel":"suelo"}</b></div><button className="analysis-open" onClick={openAnalysis}>Abrir RGB, NDVI e informe ↗</button><Chart kind="distribution" time={time}/><p className="chart-note">Distribución de celdas · NDVI sin unidades</p><div className="quantiles"><span>P10 <b>{statistics.p10.toFixed(2)}</b></span><span>Mediana <b>{statistics.median.toFixed(2)}</b></span><span>P90 <b>{statistics.p90.toFixed(2)}</b></span></div></>:<div className="pending-map"><span>◎</span><p>La capa se revela tras el vuelo.</p><button onClick={()=>{setTime(57);setView('mission')}}>Ver análisis de vegetación →</button></div>}</div>
 <div className="rail-section"><div className="section-heading"><h3>Actividad de misión</h3><span>SIMULADA</span></div><Chart kind="telemetry" time={time}/><div className="chart-legend"><span><i className="blue"/> Batería aérea</span><span><i/> Cobertura</span></div></div>
 <MaintenancePanel time={time} onThermal={()=>{setThermal(true);setCamera("local");setView("mission");scene.current?.resetCamera()}}/><SoilPanel time={time}/>
 {m.report&&<div className="mission-result"><span>✓ MISIÓN COMPLETA</span><h3>Evidencia lista para revisión</h3><p>Observación cenital, dos drones y tres muestras terrestres con metodología y control de calidad.</p><button onClick={openAnalysis}>Abrir informe profesional ↗</button></div>}

 <details className="provenance"><summary>Origen de los datos y del diseño</summary><p>Diseño conceptual inspirado en el dossier Enterprise de UPAIDOWN, páginas 4–7 y handoff 3D, secciones 2 y 5. Parcela local de 30 × 21 m, sin coordenadas reales. El NDVI se obtiene de reflectancias roja y NIR sintéticas mediante (NIR − rojo) / (NIR + rojo); mapa, histograma y estadísticas utilizan las mismas {statistics.count} celdas.</p><p>La secuencia es una simulación narrativa de 192 segundos. Los tiempos no representan velocidades ni rendimientos reales del hardware. Texturas de terreno e iluminación: Poly Haven, CC0. Hoja de vid generada con IA.</p><a href="https://polyhaven.com/a/aerial_ground_rock" target="_blank" rel="noreferrer">Textura de terreno</a> · <a href="https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky" target="_blank" rel="noreferrer">Luz del entorno</a></details>
 </fieldset></aside>}</main>
 <footer className="mission-deck"><div className="transport"><button className="play-button" disabled={!ready||!!error||recording} onClick={play} aria-label={playing?'Pausar misión':'Reproducir misión'}>{playing?'Ⅱ':'▶'}</button><button disabled={recording} aria-label="Reiniciar misión" title="Reiniciar" onClick={()=>{setTime(0);setSpeed(1);setCamera('auto');setView('mission');setThermal(false);setPlaying(false);scene.current?.resetCamera()}}>↺</button><span className="time-readout">{formatTime(time)} <small>/ 3:12</small></span><label className="speed"><span>Velocidad</span><select value={speed} disabled={recording} onChange={e=>setSpeed(+e.target.value)}><option value=".5">0,5×</option><option value="1">1×</option><option value="2">2×</option></select></label><div className="export-actions"><button disabled={!ready} onClick={capture}>Captura</button><button disabled={!m.ndvi} onClick={()=>download(new Blob([csvReport()],{type:'text/csv;charset=utf-8'}),'UPAIDOWN-ndvi-sintetico.csv')}>Datos CSV</button><button disabled={!ready} className={recording?'recording':''} onClick={()=>recording?recordStop.current?.():startRecording()}>{recording?'■ Detener vídeo':'● Grabar recorrido'}</button></div></div>
 <input className="timeline-slider" aria-label="Tiempo de la misión en segundos" type="range" min="0" max={DURATION} step=".1" disabled={recording} value={time} onChange={e=>{setTime(+e.target.value);setView('mission')}} style={{'--progress':`${time/DURATION*100}%`} as React.CSSProperties}/>
 <nav className="chapters" aria-label="Capítulos de la misión">{chapters.map((c,i)=><button key={c.at} disabled={recording} className={i===m.phase?'active':i<m.phase?'complete':''} onClick={()=>{setTime(c.at);setView('mission');scene.current?.resetCamera()}}><span>{String(i+1).padStart(2,'0')}</span>{c.short}<small>{formatTime(c.at)}</small></button>)}</nav>
 </footer>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso">×</button></div>}
 {analysis&&<AnalysisPanel time={time} rgb={rgb} onClose={()=>setAnalysis(false)}/>}
 </div>
}
