import {clamp,lerp,ROVER_SCALE,ANOMALY,pathAt,type BayState} from './mission';
export const LOCAL_AREA={x:ANOMALY.x-1.43*ROVER_SCALE,z:ANOMALY.z,width:12,depth:10,altitude:12};
export const observations=[
 {id:'PL-01',x:2.4,z:4.4,type:'stress',title:'Anomalía térmica · revisar planta',signal:'Dosel más cálido y pérdida local de vigor. Posible estrés o plaga; causa sin confirmar.',action:'Inspeccionar ambas caras de las hojas y contrastar riego. Confirmar plaga antes de tratar.',priority:'Alta',temperature:33.8},
 {id:'PL-02',x:6.6,z:4.4,type:'dry',title:'Posible tejido seco · comprobar viabilidad',signal:'Follaje seco en RGB y baja actividad vegetal simulada. No confirma que la planta haya muerto.',action:'Revisar tallo, brotes y raíces en campo antes de retirar o reponer.',priority:'Media',temperature:35.1},
 {id:'MH-01',x:0,z:.2,type:'weed',title:'Vegetación fuera de fila · posible mala hierba',signal:'Masa verde RGB fuera del dosel cultivado. Identificación botánica pendiente.',action:'Localizar el parche y confirmar si es hierba no deseada antes de intervenir.',priority:'Media',temperature:28.2},
 {id:'PL-03',x:-1.8,z:-1.2,type:'active',title:'Vegetación activa · sin alerta',signal:'Dosel continuo y temperatura de referencia. Estado visual compatible con vegetación activa.',action:'Mantener observación. La ausencia de anomalías no garantiza ausencia de plagas.',priority:'Seguimiento',temperature:28.4}
] as const;
export function localFlightOffset(b:Pick<BayState,'air'|'survey'>){const route:[number,number,number][]=[[0,0,0],[-4,0,-3],[4,0,-3],[4,0,0],[-4,0,0],[-4,0,3],[4,0,3],[0,0,0]];const p=pathAt(route,b.survey);return {x:p[0]*b.air,z:p[2]*b.air}}
export function temperatureAt(x:number,z:number){const row=Math.abs(((z+43.2+1.4)%2.8+2.8)%2.8-1.4);const canopy=row<.55&&Math.abs(z-1.6)>1.1;let t=(canopy?28.5:34)+.4*Math.sin(x*1.1+z*.8);for(const o of observations){const weight=Math.exp(-((x-o.x)**2+(z-o.z)**2)/.65);t=lerp(t,o.temperature,weight)}return t}
export function thermalColor(t:number){const stops=[[24,[33,24,81]],[28,[63,72,181]],[31,[202,52,111]],[34,[248,140,53]],[38,[255,246,162]]] as const;for(let i=1;i<stops.length;i++)if(t<=stops[i][0]){const [a,ca]=stops[i-1],[b,cb]=stops[i];return ca.map((c,k)=>Math.round(lerp(c,cb[k],clamp((t-a)/(b-a)))))}return[255,246,162]}
export function localEvidence(time:number){return {classification:'SYNTHETIC',available:time>=94,area:LOCAL_AREA,sensors:['RGB conceptual','Térmica simulada'],calibration:'NOT_AVAILABLE',observations:time>=94?observations:[],alerts:time>=94?observations.filter(o=>o.type!=='active'):[],delivery:'Local demo only; no external notification sent'}}
export function thermalSvg(){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 500" shape-rendering="crispEdges">${Array.from({length:60*50},(_,i)=>{const col=i%60,row=Math.floor(i/60),x=LOCAL_AREA.x-6+(col+.5)*.2,z=LOCAL_AREA.z-5+(row+.5)*.2;return `<rect x="${col*10}" y="${row*10}" width="10" height="10" fill="rgb(${thermalColor(temperatureAt(x,z))})"/>`}).join('')}${observations.map(o=>`<circle cx="${(o.x-LOCAL_AREA.x+6)*50}" cy="${(o.z-LOCAL_AREA.z+5)*50}" r="12" stroke="white" fill="none" stroke-width="2"/><text x="${(o.x-LOCAL_AREA.x+6)*50+15}" y="${(o.z-LOCAL_AREA.z+5)*50}" fill="white" font-size="15">${o.id}</text>`).join('')}<text x="15" y="25" fill="white" font-size="15">TÉRMICA SINTÉTICA · 120 m² · −Z ↑</text></svg>`}
