import test from 'node:test';
import assert from 'node:assert/strict';
import {cells,statistics,missionAt,DURATION,phaseIndex,chapters,telemetryUntil,summarize,csvReport,pathAt,flightPath,ROVER_SCALE,ANOMALY} from './mission';
test('NDVI map, distribution and summaries share exactly the same samples',()=>{assert.equal(statistics.count,cells.length);assert.equal(statistics.bins.reduce((n,b)=>n+b.count,0),cells.length);assert.equal(statistics.mean,cells.reduce((n,c)=>n+c.value,0)/cells.length);assert.ok(cells.every(c=>c.value>=-1&&c.value<=1));assert.ok(statistics.p10<=statistics.median&&statistics.median<=statistics.p90);assert.ok(statistics.low>0);assert.equal(csvReport().split('\n').length,cells.length+1)});
test('seek, reset and replay are deterministic with staged evidence',()=>{for(let t=0;t<=DURATION;t+=.5){assert.deepEqual(missionAt(t),missionAt(t));const m=missionAt(t);assert.ok(m.coverage>=0&&m.coverage<=1);assert.equal(m.ndvi,t>=57);assert.equal(m.sample,t>=103);assert.equal(m.report,t>=DURATION);if(m.ndvi)assert.equal(m.coverage,1);if(t>=103&&t<110)assert.ok(Math.abs(m.rover[0]+1.43*ROVER_SCALE-3.2)<1e-8);assert.ok(m.probe>=0&&m.probe<=1)}assert.equal(missionAt(-500).t,0);assert.equal(missionAt(999).t,DURATION);assert.equal(missionAt(0).sample,false);assert.equal(missionAt(0).coverage,0)});
test('phase boundaries and telemetry cannot reveal future readings',()=>{chapters.forEach((c,i)=>assert.equal(phaseIndex(c.at),i));assert.equal(telemetryUntil(22.9).length,23);assert.equal(telemetryUntil(999).length,DURATION+1);assert.equal(missionAt(102.9).sample,false);assert.equal(missionAt(103).sample,true)});
test('NDVI quantiles interpolate and bins include the upper endpoint',()=>{const s=summarize([-1,0,.5,1])!;assert.equal(s.mean,.125);assert.equal(s.median,.25);assert.equal(s.bins[0].count,1);assert.equal(s.bins[9].count,1);assert.equal(summarize([]),null)});
test('flight path is bounded and returns to its start',()=>{assert.deepEqual(pathAt(flightPath,0),flightPath[0]);assert.deepEqual(pathAt(flightPath,1),flightPath.at(-1));assert.deepEqual(pathAt(flightPath,-2),flightPath[0])});

test('bay interlocks prevent launching through closed doors and retracting under flight',async()=>{const {bayCycle}=await import('./mission');for(let p=0;p<=1;p+=.001){const b=bayCycle(p);if(b.air>0){assert.ok(b.door>.999);assert.ok(b.platform>.999)}if(b.platform>0)assert.ok(b.door>.999)}for(let t=0;t<=120;t+=.05){const m=missionAt(t);if(m.stationBay.air>0){assert.ok(m.stationBay.door>.999);assert.ok(m.stationBay.platform>.999)}if(m.roverBay.air>0){assert.equal(m.rover[0],ANOMALY.x-1.43*ROVER_SCALE);assert.ok(m.roverBay.door>.999)}}assert.equal(bayCycle(1).door,0);assert.equal(bayCycle(1).platform,0);assert.equal(bayCycle(1).air,0)});
test('NDVI is reproducible from bands and soil is excluded from canopy statistics',async()=>{const {normalizedDifference,canopyStatistics}=await import('./mission');assert.equal(normalizedDifference(0,0),null);assert.equal(normalizedDifference(-1,.5),null);assert.ok(Math.abs(normalizedDifference(.1,.5)!-2/3)<1e-12);for(const c of cells)assert.equal(c.value,normalizedDifference(c.red,c.nir));assert.equal(canopyStatistics.count,cells.filter(c=>c.canopy).length);assert.ok(canopyStatistics.mean>statistics.mean);assert.ok(canopyStatistics.low>0)});

test('Station scissor rises outside its bay and lowers only after touchdown',async()=>{const {stationCycle}=await import('./mission');for(let t=0;t<=120;t+=.02){const b=missionAt(t).stationBay;if(b.lift>0){assert.ok(b.platform>.999);assert.ok(b.door>.999)}if(b.air>0)assert.ok(b.lift>.999)}for(let p=0;p<=1;p+=.001){const b=stationCycle(p);if(b.lift>0){assert.ok(b.platform>.999);assert.ok(b.door>.999)}if(b.air>0)assert.ok(b.lift>.999)}assert.equal(missionAt(30).stationBay.lift,1);assert.equal(missionAt(72).stationBay.air,0);assert.equal(missionAt(74).stationBay.lift,0);assert.equal(missionAt(77).stationBay.platform,0);assert.equal(missionAt(80).stationBay.door,0)});
