import {officialLogo} from './branding';
import * as T from 'three';
import {LOCAL_AREA,localFlightOffset,thermalColor,temperatureAt} from './local-inspection';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RGBELoader} from 'three/addons/loaders/RGBELoader.js';
import {missionAt,bayCycle,stationCycle,ROVER_SCALE,GRID,cells,colorFor,ANOMALY,flightPath,clamp,smooth,type ViewMode,type CameraMode} from './mission';
export type SceneOptions={time:number;view:ViewMode;camera:CameraMode;ndvi:boolean;quality:'high'|'balanced';deployment:number;probe:number;bay:number;inspection?:number;thermal?:boolean;explode:boolean;selected:number};

// Public assets follow Vite's configured base in the hosted and embedded builds.
const asset=(path:string)=>`${import.meta.env.BASE_URL}${path}`;
export class FieldScene{
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(42,1,.1,400);controls:OrbitControls;
 private composer:EffectComposer;private ao:GTAOPass;private disposed=false;private frame=0;private resize:ResizeObserver;private opts:SceneOptions;private timer=new T.Clock();
 private world=new T.Group();private studio=new T.Group();private rover=new T.Group();private station=new T.Group();private drone=new T.Group();private roverDrone=new T.Group();private droneLocator=new T.Sprite();private thermalOverlay=new T.Group();private fieldOverlay=new T.Group();private marker=new T.Group();private flightLine:T.Line;private scan:T.Mesh;private mixerTime=0;
 private thermalMaterials=new Map<T.Material,T.ShaderMaterial>();
 private sensorTarget=new T.WebGLRenderTarget(320,200);private skyTexture?:T.Texture;private renderTarget?:T.WebGLRenderTarget;private loaded=false;private cameraKey='';private desired=new T.Vector3();private target=new T.Vector3();private sun:T.DirectionalLight;private currentPick=-1;
 private onPick:(n:number)=>void;private onReady:()=>void;private onError:(s:string)=>void;
 constructor(private host:HTMLElement,options:SceneOptions,onPick:(n:number)=>void,onReady:()=>void,onError:(s:string)=>void){
 this.opts=options;this.onPick=onPick;this.onReady=onReady;this.onError=onError;
 this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance',preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));this.renderer.setClearColor('#b6c3c9');this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.95;this.renderer.outputColorSpace=T.SRGBColorSpace;host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','Parcela agrícola tridimensional. Arrastra para girar y usa la rueda para acercarte.');this.renderer.domElement.tabIndex=0;
 this.scene.fog=new T.FogExp2('#b5c3c5',.003);this.scene.background=new T.Color('#b8c7cc');this.scene.add(this.droneLocator,this.world,this.studio,this.rover,this.station,this.drone,this.roverDrone,this.thermalOverlay,this.fieldOverlay,this.marker);
 this.scene.add(new T.HemisphereLight('#d0e6fa','#665e47',.85));this.sun=new T.DirectionalLight('#ffe2b0',2.7);this.sun.position.set(-22,30,18);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-28,right:28,top:26,bottom:-26,near:.1,far:95});this.sun.shadow.bias=-.00016;this.sun.shadow.normalBias=.025;this.sun.shadow.camera.updateProjectionMatrix();this.scene.add(this.sun);
 this.camera.position.set(-14,8,17);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(0,1,0);this.controls.enableDamping=true;this.controls.minDistance=.65;this.controls.maxDistance=64;this.controls.maxPolarAngle=Math.PI/2-.035;this.controls.addEventListener('start',()=>{this.cameraKey='manual'});
 const labelCanvas=document.createElement('canvas');labelCanvas.width=320;labelCanvas.height=80;const lc=labelCanvas.getContext('2d')!;lc.fillStyle='#10252ded';lc.fillRect(0,0,320,64);lc.strokeStyle='#b3e5d3';lc.lineWidth=3;lc.strokeRect(1,1,318,62);lc.fillStyle='#fff';lc.font='bold 24px Arial';lc.fillText('WALL-AI · RGB / T',25,41);lc.beginPath();lc.moveTo(150,64);lc.lineTo(170,64);lc.lineTo(160,80);lc.fill();this.droneLocator.material=new T.SpriteMaterial({map:new T.CanvasTexture(labelCanvas),depthTest:false});this.droneLocator.scale.set(4.1,1.025,1);this.droneLocator.renderOrder=20;this.rover.scale.setScalar(ROVER_SCALE);this.makeGround();this.makeVegetation();this.makeLocalThermal();this.makeOverlay();this.makeStudio();
 const route=flightPath.slice(2,-2).map(p=>new T.Vector3(p[0],.12,p[2]));this.flightLine=new T.Line(new T.BufferGeometry().setFromPoints(route),new T.LineDashedMaterial({color:'#d7e8d6',transparent:true,opacity:.45,dashSize:.5,gapSize:.3}));this.flightLine.computeLineDistances();this.world.add(this.flightLine);
 this.scan=new T.Mesh(new T.PlaneGeometry(5,4),new T.MeshBasicMaterial({color:'#5be4d2',transparent:true,opacity:.1,depthWrite:false,side:T.DoubleSide}));this.scan.rotation.x=-Math.PI/2;this.world.add(this.scan);
 const postTarget=new T.WebGLRenderTarget(1,1,{type:T.HalfFloatType,samples:4});this.composer=new EffectComposer(this.renderer,postTarget);this.composer.addPass(new RenderPass(this.scene,this.camera));this.ao=new GTAOPass(this.scene,this.camera);this.ao.updateGtaoMaterial({radius:.65,distanceExponent:1,thickness:1,scale:1,samples:8});this.ao.blendIntensity=.8;this.composer.addPass(this.ao);this.composer.addPass(new OutputPass());
 this.resize=new ResizeObserver(()=>this.resizeCanvas());this.resize.observe(host);this.resizeCanvas();this.renderer.domElement.addEventListener('click',this.pick);this.renderer.domElement.addEventListener('webglcontextlost',this.contextLost);void this.load();this.animate();
 }
 private resizeCanvas(){const {width,height}=this.host.getBoundingClientRect();this.renderer.setSize(Math.max(1,width),Math.max(1,height));this.camera.aspect=Math.max(1,width)/Math.max(1,height);this.camera.updateProjectionMatrix();this.composer?.setSize(Math.max(1,width),Math.max(1,height))}
 private contextLost=(e:Event)=>{e.preventDefault();this.onError('La vista 3D se ha detenido. Puedes continuar con los gráficos o recargar la escena.')};
 private makeGround(){const geo=new T.PlaneGeometry(220,220,180,180);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i);const dist=Math.max(Math.abs(x)-25,Math.abs(z)-20,0);pos.setY(i,-.06+Math.sin(x*.18)*Math.sin(z*.23)*.055+smooth(dist/65)*Math.sin(x*.057+z*.023)*.5)}geo.computeVertexNormals();const mat=new T.MeshStandardMaterial({color:'#c2a47d',roughness:1});const ground=new T.Mesh(geo,mat);ground.receiveShadow=true;this.world.add(ground);
 const loader=new T.TextureLoader();const maps:[string,'map'|'normalMap'|'roughnessMap'][]=[['ground-color.jpg','map'],['ground-normal.jpg','normalMap'],['ground-roughness.jpg','roughnessMap']];for(const [file,key]of maps)loader.load(asset(`textures/${file}`),texture=>{if(this.disposed){texture.dispose();return}texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(45,45);texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());if(key==='map')texture.colorSpace=T.SRGBColorSpace;mat[key]=texture;if(key==='normalMap')mat.normalScale.set(.55,.55);mat.needsUpdate=true},undefined,()=>{});
 // Distant ridges keep the horizon grounded without remote map dependencies.
 const ridgeGeo=new T.PlaneGeometry(360,180,180,90);ridgeGeo.rotateX(-Math.PI/2);const ridgePos=ridgeGeo.attributes.position;for(let i=0;i<ridgePos.count;i++){const x=ridgePos.getX(i),z=ridgePos.getZ(i)-125;const fade=smooth((-z-35)/60);const h=fade*(7+5*Math.sin(x*.032+z*.01)+3*Math.sin(x*.077-z*.025)+1.3*Math.sin(x*.21+z*.13)+.6*Math.sin(x*.81+z*.65)+.3*Math.sin(x*1.8-z*1.3));ridgePos.setXYZ(i,x,h-.25,z)}ridgeGeo.computeVertexNormals();const rc=[];for(let i=0;i<ridgePos.count;i++){const x=ridgePos.getX(i),z=ridgePos.getZ(i),n=(Math.sin(x*.22+z*.31)+Math.sin(x*.71-z*.61))*.5;const c=new T.Color().setRGB(.19+n*.04,.24+n*.055,.12+n*.035);rc.push(c.r,c.g,c.b)}ridgeGeo.setAttribute('color',new T.Float32BufferAttribute(rc,3));const ridgeMat=new T.MeshStandardMaterial({vertexColors:true,roughness:1});const ridge=new T.Mesh(ridgeGeo,ridgeMat);ridge.receiveShadow=true;this.world.add(ridge);loader.load(asset('textures/ground-color.jpg'),t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(65,35);t.colorSpace=T.SRGBColorSpace;ridgeMat.map=t;ridgeMat.needsUpdate=true});

 }
 private makeVegetation(){let seed=37;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};const branches:T.Matrix4[]=[],trunks:T.Matrix4[]=[],leaves:T.Matrix4[]=[],stakes:T.Matrix4[]=[];const leafColors:T.Color[]=[];const obj=new T.Object3D();
 for(let row=0;row<22;row++){const z=-43.2+row*2.8;if(Math.abs(z-1.6)<1.1)continue;for(let col=0;col<42;col++){const x=-48+col*2.1;if(Math.abs(x+14)<2.5||(x>7&&x<12&&z>-8&&z<-2))continue;obj.position.set(x,.58,z);obj.scale.set(.06,1.05,.055);obj.rotation.set(0,rand()*6,.06);obj.updateMatrix();trunks.push(obj.matrix.clone());if(col%4===0){obj.position.set(x,.85,z);obj.scale.set(.045,1.75,.045);obj.rotation.set(0,0,0);obj.updateMatrix();stakes.push(obj.matrix.clone())}
 // Trained woody cordons and upright shoots carry each leaf, rather than floating foliage.
 const segment=(a:T.Vector3,b:T.Vector3,r:number)=>{obj.position.copy(a).add(b).multiplyScalar(.5);obj.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),b.clone().sub(a).normalize());obj.scale.set(r,a.distanceTo(b),r);obj.updateMatrix();branches.push(obj.matrix.clone())};
 segment(new T.Vector3(x-.92,1.05,z),new T.Vector3(x+.92,1.12,z),.025);
 for(let shoot=0;shoot<7;shoot++){const sx=x-.85+shoot*.28,top=1.55+rand()*.4,bend=(rand()-.5)*.35;segment(new T.Vector3(sx,1.08,z),new T.Vector3(sx+bend,top,z+.08),.008);
 for(let l=0;l<7;l++){if(Math.abs(x-6.6)<.5&&Math.abs(z-4.4)<.5&&l%3===0)continue;const h=l/7,side=l%2?1:-1;obj.position.set(sx+bend*h+side*.10,1.07+(top-1.07)*h,z+side*(.1+rand()*.18));obj.rotation.set(-.6+rand()*1.2,rand()*6.28,.3+rand()*.7);obj.scale.set(.22+rand()*.12,.24+rand()*.13,1);obj.updateMatrix();leaves.push(obj.matrix.clone());leafColors.push(Math.abs(x-6.6)<.5&&Math.abs(z-4.4)<.5?new T.Color('#a89551'):new T.Color().setRGB(.55+rand()*.35,.60+rand()*.25,.38+rand()*.35))}}}

 for(const [a,b]of [[-48,-16.5],[-11.5,38]]){const wire=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(a,1.25,z),new T.Vector3(b,1.25,z)]),new T.LineBasicMaterial({color:'#6d7163'}));this.world.add(wire)}}
 const instantiate=(geometry:T.BufferGeometry,material:T.Material,matrices:T.Matrix4[],shadow:boolean)=>{const inst=new T.InstancedMesh(geometry,material,matrices.length);matrices.forEach((m,i)=>inst.setMatrixAt(i,m));inst.castShadow=shadow;inst.receiveShadow=true;this.world.add(inst);return inst};instantiate(new T.CylinderGeometry(.65,1,1,5),new T.MeshStandardMaterial({color:'#514333',roughness:1}),branches,true);instantiate(new T.CylinderGeometry(1,1,1,8),new T.MeshStandardMaterial({color:'#605043',roughness:1}),trunks,true);instantiate(new T.BoxGeometry(1,1,1),new T.MeshStandardMaterial({color:'#8b8573',roughness:.9}),stakes,true);const leafMaterial=new T.MeshStandardMaterial({color:'#ffffff',roughness:.85,side:T.DoubleSide,alphaTest:.48});const leafGeo=new T.PlaneGeometry(1,1,4,4);const lp=leafGeo.attributes.position;for(let i=0;i<lp.count;i++)lp.setZ(i,.18*Math.abs(lp.getX(i))+.08*Math.sin(lp.getY(i)*5));leafGeo.computeVertexNormals();const foliage=instantiate(leafGeo,leafMaterial,leaves,true);foliage.visible=false;leafColors.forEach((c,i)=>foliage.setColorAt(i,c));new T.TextureLoader().load(asset('textures/grapevine-leaf.png'),texture=>{if(this.disposed){texture.dispose();return}texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=8;leafMaterial.map=texture;leafMaterial.needsUpdate=true;foliage.visible=true},undefined,()=>{});
 // Ground cover with deterministic placement, leaving the mission lane clear.
 const grassMatrices:T.Matrix4[]=[];for(let i=0;i<4000;i++){const x=(rand()-.5)*95,z=(rand()-.5)*80;if(Math.abs(z-1.6)<1.5||Math.hypot(x-9,z+5)<3)continue;obj.position.set(x,.10,z);obj.rotation.set(0,rand()*6,(rand()-.5)*.4);obj.scale.set(.02+rand()*.04,.08+rand()*.18,.018);obj.updateMatrix();grassMatrices.push(obj.matrix.clone())}instantiate(new T.ConeGeometry(1,1,5),new T.MeshStandardMaterial({color:'#7b8145',roughness:1}),grassMatrices,false);
 const pebbles:T.Matrix4[]=[];for(let i=0;i<550;i++){obj.position.set((rand()-.5)*70,.025,(rand()-.5)*50);obj.rotation.set(rand()*3,rand()*6,rand()*3);obj.scale.set(.025+rand()*.09,.015+rand()*.03,.03+rand()*.06);obj.updateMatrix();pebbles.push(obj.matrix.clone())}instantiate(new T.DodecahedronGeometry(1,0),new T.MeshStandardMaterial({color:'#938977',roughness:1}),pebbles,false);const weed:T.Matrix4[]=[];for(let i=0;i<100;i++){obj.position.set((rand()-.5)*1.1,.05+rand()*.25,.2+(rand()-.5)*.8);obj.rotation.set(-Math.PI/2+rand(),rand()*6,rand());obj.scale.set(.10+rand()*.1,.15+rand()*.1,1);obj.updateMatrix();weed.push(obj.matrix.clone())}instantiate(leafGeo,leafMaterial,weed,true);for(let row=0;row<22;row++){const z=-43.2+row*2.8;if(Math.abs(z-1.6)<1.1)continue;this.world.add(new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(-48,.065,z+.13),new T.Vector3(38,.065,z+.13)]),new T.LineBasicMaterial({color:'#34362b'})))}
 }
 private makeLocalThermal(){const p:number[]=[],c:number[]=[];for(let row=0;row<50;row++)for(let col=0;col<60;col++){const x=LOCAL_AREA.x-6+(col+.5)*.2,z=LOCAL_AREA.z-5+(row+.5)*.2,color=thermalColor(temperatureAt(x,z)).map(v=>v/255);for(const [dx,dz]of [[-.1,-.1],[.1,-.1],[.1,.1],[-.1,-.1],[.1,.1],[-.1,.1]]){p.push(x+dx,.18,z+dz);c.push(...color)}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(p,3));geo.setAttribute('color',new T.Float32BufferAttribute(c,3));this.thermalOverlay.add(new T.Mesh(geo,new T.MeshBasicMaterial({vertexColors:true,side:T.DoubleSide,transparent:true,opacity:.7,depthWrite:false})));const outline=new T.Line(new T.BufferGeometry().setFromPoints([[-6,-5],[6,-5],[6,5],[-6,5],[-6,-5]].map(([x,z])=>new T.Vector3(LOCAL_AREA.x+x,.22,LOCAL_AREA.z+z))),new T.LineBasicMaterial({color:'#f8ce84'}));this.thermalOverlay.add(outline)}
 private makeOverlay(){const positions:number[]=[],colors:number[]=[];for(const c of cells){const dx=GRID.width/GRID.cols/2,dz=GRID.depth/GRID.rows/2;const rgb=colorFor(c.value).map(n=>n/255);for(const [x,z]of [[-dx,-dz],[dx,-dz],[dx,dz],[-dx,-dz],[dx,dz],[-dx,dz]]){positions.push(c.x+x,.14,c.z+z);colors.push(...rgb)}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const field=new T.Mesh(geo,new T.MeshBasicMaterial({vertexColors:true,transparent:true,opacity:.75,side:T.DoubleSide,depthWrite:false}));field.name='ndvi-surface';this.fieldOverlay.add(field);
 const ring=new T.Mesh(new T.RingGeometry(.8,.86,64),new T.MeshBasicMaterial({color:'#f1bc67',side:T.DoubleSide,transparent:true,opacity:.95}));ring.rotation.x=-Math.PI/2;ring.position.set(ANOMALY.x,.19,ANOMALY.z);this.marker.add(ring);
 }
 private makeStudio(){const disc=new T.Mesh(new T.CylinderGeometry(4.2,4.3,.12,96),new T.MeshStandardMaterial({color:'#c1c7c4',roughness:.75,metalness:.08}));disc.position.y=-.07;disc.receiveShadow=true;this.studio.add(disc);const ground=new T.Mesh(new T.PlaneGeometry(400,400),new T.MeshStandardMaterial({color:'#929f9f',roughness:.95}));ground.rotation.x=-Math.PI/2;ground.position.y=-.15;ground.receiveShadow=true;this.studio.add(ground)}
 private addBranding(){
 const texture=new T.TextureLoader().load(officialLogo);texture.colorSpace=T.SRGBColorSpace;texture.anisotropy=8;const mat=new T.MeshStandardMaterial({map:texture,transparent:true,depthWrite:false,roughness:.65,metalness:.05,polygonOffset:true,polygonOffsetFactor:-1});
 for(const side of [-1,1]){const label=new T.Mesh(new T.PlaneGeometry(1.28,.277),mat);label.position.set(side*1.02,1.46,-.15);label.rotation.y=side*Math.PI/2;this.rover.add(label)}
 const stationLabel=new T.Mesh(new T.PlaneGeometry(1.38,.299),mat);stationLabel.position.set(0,.33,-.036);const front=this.station.getObjectByName('station_front');front?.add(stationLabel);stationLabel.rotation.y=Math.PI;
 const skin=document.createElement('canvas');skin.width=skin.height=128;const c=skin.getContext('2d')!;const pixels=c.createImageData(128,128);let seed=917;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const n=210+seed%35;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=n;pixels.data[i+3]=255}c.putImageData(pixels,0,0);const micro=new T.CanvasTexture(skin);micro.wrapS=micro.wrapT=T.RepeatWrapping;micro.repeat.set(8,8);for(const root of [this.rover,this.station])root.traverse(obj=>{if(obj instanceof T.Mesh){for(const material of Array.isArray(obj.material)?obj.material:[obj.material])if(material instanceof T.MeshStandardMaterial&&!material.map){material.roughnessMap=micro;material.needsUpdate=true}}});
 }
 private async load(){try{const loader=new GLTFLoader();const models=await Promise.all(['rover','sentinel','drone'].map(n=>loader.loadAsync(asset(`models/${n}.glb`))));if(this.disposed){for(const model of models)this.disposeObject(model.scene);return}for(const [i,g]of [this.rover,this.station,this.drone].entries()){g.add(models[i].scene);g.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}})}this.roverDrone.add(models[2].scene.clone(true));const thermalSensor=new T.Mesh(new T.BoxGeometry(.085,.11,.14),new T.MeshStandardMaterial({color:'#252e34',metalness:.6,roughness:.35}));thermalSensor.position.set(.12,-.23,0);this.roverDrone.add(thermalSensor);const thermalLens=new T.Mesh(new T.CylinderGeometry(.028,.028,.02,20),new T.MeshStandardMaterial({color:'#5b3a53',metalness:.7,roughness:.12}));thermalLens.rotation.x=Math.PI/2;thermalLens.position.set(.12,-.23,-.085);this.roverDrone.add(thermalLens);this.drone.scale.setScalar(.80);this.roverDrone.scale.setScalar(.60*ROVER_SCALE);this.roverDrone.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});this.addBranding();this.loaded=true;this.onReady();const hdr=await new RGBELoader().loadAsync(asset('textures/sky.hdr'));if(this.disposed){hdr.dispose();return}this.skyTexture=hdr;hdr.mapping=T.EquirectangularReflectionMapping;const pmrem=new T.PMREMGenerator(this.renderer);this.renderTarget=pmrem.fromEquirectangular(hdr);this.scene.environment=this.renderTarget.texture;this.scene.environmentIntensity=.7;this.scene.background=hdr;this.scene.backgroundIntensity=.7;pmrem.dispose()}catch{if(!this.loaded)this.onError('No se han podido cargar los modelos. Los datos y controles siguen disponibles; recarga para volver a intentarlo.')}}
 update(options:SceneOptions){const qualityChanged=this.opts.quality!==options.quality;this.opts=options;if(qualityChanged){this.renderer.setPixelRatio(Math.min(devicePixelRatio,options.quality==='high'?1.85:1.15));this.composer.setPixelRatio(this.renderer.getPixelRatio());this.sun.shadow.mapSize.setScalar(options.quality==='high'?2048:1024);this.sun.shadow.map?.dispose();this.sun.shadow.map=null;this.resizeCanvas()}}
 private pick=(event:MouseEvent)=>{if(!this.opts.ndvi||!this.fieldOverlay.visible)return;const r=this.renderer.domElement.getBoundingClientRect(),pointer=new T.Vector2((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1),ray=new T.Raycaster();ray.setFromCamera(pointer,this.camera);const hits=ray.intersectObjects(this.fieldOverlay.children);if(hits[0]?.faceIndex!=null){const i=Math.floor(hits[0].faceIndex/2);if(cells[i]){this.currentPick=i;this.onPick(i)}}};
 private animate=()=>{if(this.disposed)return;this.frame=requestAnimationFrame(this.animate);const dt=Math.min(this.timer.getDelta(),.06);this.mixerTime+=dt;const o=this.opts,m=missionAt(o.time),mission=o.view==='mission';this.world.visible=mission;this.studio.visible=!mission;this.rover.visible=o.view!=='sentinel';this.station.visible=o.view!=='rover';this.drone.visible=o.view!=='rover';this.roverDrone.visible=o.view!=='sentinel';this.thermalOverlay.visible=mission&&!m.sampling&&((!!o.thermal&&m.t>=94)||m.roverBay.air>0);this.thermalOverlay.children[0].visible=!!o.thermal&&m.t>=94;this.fieldOverlay.visible=mission&&!m.sampling&&o.ndvi&&m.ndvi&&!this.thermalOverlay.visible;const overlayMaterial=(this.fieldOverlay.children[0] as T.Mesh).material as T.MeshBasicMaterial;overlayMaterial.opacity=m.phase===3?.70:.20;this.marker.visible=mission&&m.ndvi&&!m.sampling;this.flightLine.visible=m.t>=28&&m.t<72;this.scan.visible=m.t>=30&&m.t<57;
 this.scene.background=mission&&this.skyTexture?this.skyTexture:new T.Color(mission?'#b8c7cc':'#b8c2c3');this.scene.fog=mission?new T.FogExp2('#b5c3c5',.003):null;
 if(mission)this.rover.position.set(...m.rover);else this.rover.position.set(0,0,0);this.rover.rotation.y=mission?m.roverYaw:-.4;this.station.position.set(mission?9:0,0,mission?-5:0);
 const height=mission?m.mast:o.deployment;for(const name of ['mast_stage_02','mast_stage_03']){const joint=this.station.getObjectByName(name);if(joint)joint.position.y=height*1.2}
 const manualBay=o.inspection?bayCycle(o.inspection):{door:smooth(o.bay/.5),platform:smooth((o.bay-.5)/.5),air:0,survey:0};
 const sb=mission?m.stationBay:o.inspection?stationCycle(o.inspection):{...manualBay,platform:smooth((o.bay-.3)/.35),door:smooth(o.bay/.3),lift:smooth((o.bay-.65)/.35)},rb=mission?m.roverBay:manualBay;
 const lid=this.station.getObjectByName('sentinel_lid');if(lid)lid.rotation.x=0;
 const front=this.station.getObjectByName('station_front');if(front)front.rotation.x=-sb.door*Math.PI/2;
 const rails=this.station.getObjectByName('station_rails');if(rails)rails.position.z=-sb.platform*.95;const tray=this.station.getObjectByName('station_tray');if(tray)tray.position.z=-sb.platform*1.85;
 const lift=this.station.getObjectByName('station_lift');const deckHeight=.10+sb.lift*.52;if(lift)lift.position.y=deckHeight;const span=deckHeight-.04,angle=Math.acos(span/.90);for(const side of [-1,1]){for(const direction of [-1,1]){const arm=this.station.getObjectByName(`scissor_${side}_${direction}`);if(arm){arm.position.set(side*.66+direction*.018,span/2,0);arm.rotation.x=direction*angle}}const hinge=this.station.getObjectByName(`scissor_hinge_${side}`);if(hinge)hinge.position.y=span/2}
 const wind=this.station.getObjectByName('anemometer');if(wind)wind.rotation.y=this.mixerTime*.6;
 const probe=this.rover.getObjectByName('soil_probe');if(probe)probe.position.y=-(mission?m.probe:o.probe)*.48;
 const roverLid=this.rover.getObjectByName('rover_lid');if(roverLid)roverLid.rotation.x=rb.door*1.92;
 const roverPlatform=this.rover.getObjectByName('rover_platform');if(roverPlatform)roverPlatform.position.y=1.23+rb.platform*.62;
 for(const name of ['track_left','track_right']){const track=this.rover.getObjectByName(name);if(track)track.position.x=!mission?(name==='track_left'?-1:1)*(o.explode?.75:0):0}
 for(const side of [-1,1])for(let i=0;i<64;i++){const tread=this.rover.getObjectByName(`tread_${side}_${i}`);if(!tread)continue;const length=3.76+Math.PI*.70;const distance=mission?m.travelled/ROVER_SCALE:0;const u=((i/64*length+distance)%length+length)%length;let z,y,a;if(u<1.88){z=-.94+u;y=.75;a=0}else if(u<1.88+Math.PI*.35){a=(u-1.88)/.35;z=.94+Math.sin(a)*.35;y=.4+Math.cos(a)*.35}else if(u<3.76+Math.PI*.35){z=.94-(u-1.88-Math.PI*.35);y=.05;a=Math.PI}else{a=Math.PI+(u-3.76-Math.PI*.35)/.35;z=-.94+Math.sin(a)*.35;y=.4+Math.cos(a)*.35}tread.position.set(0,y,z);tread.rotation.x=a}
 const dock=new T.Vector3(0,1.9+height*2.4+.12+deckHeight+.065/2+.33*.80,-sb.platform*1.85).add(this.station.position);
 this.drone.position.copy(dock);
 if(mission&&sb.air>0){const survey=m.drone;this.drone.position.lerp(new T.Vector3(...survey),sb.air);this.drone.position.y=dock.y+sb.air*(10-dock.y)}else if(!mission)this.drone.position.add(new T.Vector3(Math.sin(sb.survey*Math.PI)*1.3,sb.air*2.2,-sb.air*.4));
 this.drone.rotation.y=0;
 this.rover.updateMatrixWorld(true);const roverDock=new T.Vector3(0,1.23+rb.platform*.62+.025+.33*.60,.1);this.rover.localToWorld(roverDock);this.roverDrone.position.copy(roverDock);const localOffset=localFlightOffset(rb);this.roverDrone.position.y+=rb.air*(LOCAL_AREA.altitude-roverDock.y);this.roverDrone.position.x+=localOffset.x;this.roverDrone.position.z+=localOffset.z;this.roverDrone.rotation.y=this.rover.rotation.y;
 for(const [aircraft,state]of [[this.drone,sb],[this.roverDrone,rb]] as const){for(let i=0;i<6;i++){const rotor=aircraft.getObjectByName(`rotor_${i}`);if(rotor)rotor.rotation.y=state.air>0?o.time*50*(i%2?1:-1)+(o.inspection??0)*500:0}}
 this.scan.position.set(this.drone.position.x,.2,this.drone.position.z);
 const selected=cells[o.selected];if(selected){this.marker.position.set(selected.x-ANOMALY.x,0,selected.z-ANOMALY.z)}
 let focus=o.camera;if(!mission)focus=o.view==='rover'?(o.probe>0?'probe':'rover'):'sentinel';else if(focus==='auto')focus=m.phase===0?'overview':m.phase===1?'sentinel':m.phase===2?(m.t<33?'sentinel':m.t<39?'aircraft':'drone'):m.phase===3?'anomaly':m.phase===4?(m.roverBay.air>.05?(m.t<88?'aircraft':'local'):'rover'):m.sampling?'probe':m.moving?'rover':'overview';const key=`${o.view}:${o.camera}:${focus}`;const manual=this.cameraKey==='manual';if(this.lastOptionsKey!==`${o.view}:${o.camera}`){this.cameraKey=key;this.lastOptionsKey=`${o.view}:${o.camera}`}else if(!manual)this.cameraKey=key;
 if(this.cameraKey!=='manual'){
 const rp=this.rover.position,sp=this.station.position,dp=this.drone.position;
 if(focus==='aircraft'){const craft=m.t>=80?this.roverDrone:this.drone;this.target.copy(craft.position);this.desired.copy(craft.position).add(new T.Vector3(2.0,1.0,2.5))}
 else if(focus==='probe'){const point=new T.Vector3(0,.30,-1.43);this.rover.localToWorld(point);this.target.copy(point);this.desired.copy(point).add(mission?new T.Vector3(1.65,.65,1.65):new T.Vector3(1.6,.65,-1.8))}
 else if(focus==='sensors'){const point=new T.Vector3(0,1.8,-1.32);this.rover.localToWorld(point);this.target.copy(point);this.desired.copy(point).add(mission?new T.Vector3(2.2,.55,1.4):new T.Vector3(1.2,.55,-2.4))}
 else if(focus==='local'){this.target.set(LOCAL_AREA.x,1+m.roverBay.air*5,LOCAL_AREA.z);this.desired.set(LOCAL_AREA.x+15,18,LOCAL_AREA.z+20)}
 else if(focus==='rover'){this.target.copy(rp).add(new T.Vector3(0,mission?.75:1.0+rb.air*4.5,0));this.desired.copy(rp).add(mission?new T.Vector3(5.4,2.4,.35):new T.Vector3(5.5+rb.air*3,4.7+rb.air*7,-6.3-rb.air*9))}
 else if(focus==='sentinel'){this.target.copy(sp).add(new T.Vector3(0,mission?3:3.3,0));this.desired.copy(sp).add(new T.Vector3(7.5,6.8,-9))}
 else if(focus==='drone'){this.target.copy(dp).setY(.2);this.desired.copy(dp).add(new T.Vector3(.01,2,.01));this.controls.maxPolarAngle=Math.PI/2-.001}
 else if(focus==='anomaly'){this.target.set(-2,0,0);this.desired.set(0,25,20)}
 else{this.target.set(0,1,-1);this.desired.set(-16+Math.sin(m.t*.02)*1.7,8.5,18)}
 const a=1-Math.exp(-dt*1.8);this.camera.position.lerp(this.desired,a);this.controls.target.lerp(this.target,a)}
 this.controls.update();this.droneLocator.visible=mission&&rb.air>.05;this.droneLocator.position.copy(this.roverDrone.position).add(new T.Vector3(0,.9,0));this.ao.enabled=o.quality==='high';this.composer.render()
 };
 private lastOptionsKey='';
 resetCamera(){this.cameraKey='';this.lastOptionsKey=''}
 drawRoverFrame(canvas:HTMLCanvasElement,time:number,eye:'left'|'right'='left'){
 const m=missionAt(time),rotation=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),m.roverYaw);const origin=new T.Vector3(eye==='left'?-.18:.18,2.20,-1.36).multiplyScalar(ROVER_SCALE).applyQuaternion(rotation).add(new T.Vector3(...m.rover));const direction=new T.Vector3(0,-.09,-1).applyQuaternion(rotation);const camera=new T.PerspectiveCamera(80,1.6,.03,180);camera.position.copy(origin);camera.lookAt(origin.clone().add(direction));const visible=this.rover.visible;this.rover.visible=false;try{this.renderSensorCamera(canvas,camera)}finally{this.rover.visible=visible}
 }
 drawSensorFrame(canvas:HTMLCanvasElement,x:number,z:number,thermal=false){const camera=new T.OrthographicCamera(-6,6,3.75,-3.75,.1,100);camera.position.set(x,30,z);camera.up.set(0,0,-1);camera.lookAt(x,0,z);this.renderSensorCamera(canvas,camera,thermal)}
 private thermalMaterial(source:T.Material){
 let result=this.thermalMaterials.get(source);if(result)return result;
 const original=source as T.MeshStandardMaterial;
 result=new T.ShaderMaterial({side:source.side,uniforms:{surfaceMap:{value:original.map??null},hasMap:{value:!!original.map},cutoff:{value:original.alphaTest||0}},
 vertexShader:`varying vec2 surfaceUv;varying vec3 fieldPosition;
 void main(){surfaceUv=uv;vec4 p=vec4(position,1.0);
 #ifdef USE_INSTANCING
 p=instanceMatrix*p;
 #endif
 vec4 world=modelMatrix*p;fieldPosition=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,
 fragmentShader:`uniform sampler2D surfaceMap;uniform bool hasMap;uniform float cutoff;varying vec2 surfaceUv;varying vec3 fieldPosition;
 vec3 palette(float t){vec3 a=vec3(33.,24.,81.),b=vec3(63.,72.,181.),c=vec3(202.,52.,111.),d=vec3(248.,140.,53.),e=vec3(255.,246.,162.);if(t<28.)return mix(a,b,clamp((t-24.)/4.,0.,1.))/255.;if(t<31.)return mix(b,c,(t-28.)/3.)/255.;if(t<34.)return mix(c,d,(t-31.)/3.)/255.;return mix(d,e,clamp((t-34.)/4.,0.,1.))/255.;}
 void main(){vec4 texel=hasMap?texture2D(surfaceMap,surfaceUv):vec4(1.);if(texel.a<cutoff)discard;
 vec2 p=fieldPosition.xz;float leaf=step(.25,fieldPosition.y)*step(fieldPosition.y,2.4);
 float temp=mix(34.,28.5,leaf)+.4*sin(p.x*1.1+p.y*.8);
 temp=mix(temp,33.8,exp(-dot(p-vec2(2.4,4.4),p-vec2(2.4,4.4))/.65));
 temp=mix(temp,35.1,exp(-dot(p-vec2(6.6,4.4),p-vec2(6.6,4.4))/.65));
 temp=mix(temp,28.2,exp(-dot(p-vec2(0.,.2),p-vec2(0.,.2))/.65));
 temp=mix(temp,28.4,exp(-dot(p-vec2(-1.8,-1.2),p-vec2(-1.8,-1.2))/.65));
 float detail=hasMap?(dot(texel.rgb,vec3(.2126,.7152,.0722))-.5)*.6:0.;gl_FragColor=vec4(palette(temp+detail),1.);}`});
 this.thermalMaterials.set(source,result);return result;
 }
 private renderSensorCamera(canvas:HTMLCanvasElement,camera:T.Camera,thermal=false){
 if(!this.loaded)return;const hidden=[this.droneLocator,this.fieldOverlay,this.thermalOverlay,this.marker,this.scan,this.flightLine,this.drone,this.roverDrone];const previous=hidden.map(o=>o.visible);hidden.forEach(o=>o.visible=false);const restored:{mesh:T.Mesh;material:T.Material|T.Material[]}[]=[];if(thermal)for(const root of [this.world,this.rover,this.station])root.traverse(o=>{if(o instanceof T.Mesh){restored.push({mesh:o,material:o.material});o.material=Array.isArray(o.material)?o.material.map(m=>this.thermalMaterial(m)):this.thermalMaterial(o.material)}});const target=this.renderer.getRenderTarget();try{this.sensorTarget.texture.colorSpace=T.SRGBColorSpace;this.renderer.setRenderTarget(this.sensorTarget);this.renderer.render(this.scene,camera);const pixels=new Uint8Array(320*200*4);this.renderer.readRenderTargetPixels(this.sensorTarget,0,0,320,200,pixels);const ctx=canvas.getContext('2d')!;const img=ctx.createImageData(320,200);for(let row=0;row<200;row++)img.data.set(pixels.subarray((199-row)*1280,(200-row)*1280),row*1280);ctx.putImageData(img,0,0)}finally{restored.forEach(({mesh,material})=>mesh.material=material);hidden.forEach((o,i)=>o.visible=previous[i]);this.renderer.setRenderTarget(target)}
 }
 aerialSnapshot(){
 const size=this.renderer.getSize(new T.Vector2()),ratio=this.renderer.getPixelRatio();const visibility=[this.droneLocator,this.world,this.studio,this.rover,this.station,this.drone,this.roverDrone,this.thermalOverlay,this.fieldOverlay,this.marker,this.scan,this.flightLine].map(o=>[o,o.visible] as const);
 this.world.visible=true;this.studio.visible=false;for(const o of [this.droneLocator,this.rover,this.station,this.drone,this.roverDrone,this.thermalOverlay,this.fieldOverlay,this.marker,this.scan,this.flightLine])o.visible=false;
 const camera=new T.OrthographicCamera(-GRID.width/2,GRID.width/2,GRID.depth/2,-GRID.depth/2,.1,150);camera.position.set(GRID.x,70,GRID.z);camera.up.set(0,0,-1);camera.lookAt(GRID.x,0,GRID.z);this.renderer.setPixelRatio(1);this.renderer.setSize(1200,840,false);this.renderer.render(this.scene,camera);const url=this.renderer.domElement.toDataURL('image/jpeg',.92);for(const [o,v]of visibility)o.visible=v;this.renderer.setPixelRatio(ratio);this.renderer.setSize(size.x,size.y,false);this.composer.render();return url;
 }
 async screenshot(){return new Promise<Blob|null>(resolve=>this.renderer.domElement.toBlob(resolve,'image/png'))}
 canvas(){return this.renderer.domElement}
 private disposeObject(root:T.Object3D){root.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){o.geometry.dispose();for(const mat of Array.isArray(o.material)?o.material:[o.material]){for(const value of Object.values(mat))if(value instanceof T.Texture)value.dispose();mat.dispose()}}})}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.resize.disconnect();this.controls.dispose();this.renderer.domElement.removeEventListener('click',this.pick);this.renderer.domElement.removeEventListener('webglcontextlost',this.contextLost);this.disposeObject(this.scene);this.skyTexture?.dispose();this.renderTarget?.dispose();this.sensorTarget.dispose();this.thermalMaterials.forEach(m=>m.dispose());this.thermalMaterials.clear();this.droneLocator.material.map?.dispose();this.droneLocator.material.dispose();this.composer.dispose();this.ao.dispose();this.renderer.dispose();this.renderer.domElement.remove()}
}
