import {useEffect,useRef,useState} from 'react';
import {bandsAt,normalizedDifference,colorFor,missionAt} from './mission';
import {LOCAL_AREA,localFlightOffset,temperatureAt,thermalColor} from './local-inspection';
import type {FieldScene} from './scene';
export type SensorMode='rgb'|'thermal'|'spectral'|'ndvi';
export function SensorPanel({time,playing,scene}:{time:number;playing:boolean;scene:FieldScene|null}){const [mode,setMode]=useState<SensorMode>('rgb');const canvas=useRef<HTMLCanvasElement>(null);const m=missionAt(time),local=time>=80;const offset=localFlightOffset(m.roverBay),x=local?LOCAL_AREA.x+offset.x:m.drone[0],z=local?LOCAL_AREA.z+offset.z:m.drone[2];const flying=local?m.roverBay.air>0:m.stationBay.air>0;const acquired=local?time>=94:time>=57;
 useEffect(()=>{const el=canvas.current,ctx=el?.getContext('2d');if(!el||!ctx)return;if(time<33||(local&&time<85.4)){ctx.fillStyle='#132730';ctx.fillRect(0,0,320,200);ctx.fillStyle='#b9d0da';ctx.font='15px Arial';ctx.fillText('Esperando adquisición del dron',45,105);return;}if((mode==='rgb'||mode==='thermal')&&scene){scene.drawSensorFrame(el,x,z,mode==='thermal');return}const data=ctx.createImageData(320,200);for(let row=0;row<200;row++)for(let col=0;col<320;col++){const px=x+(col/320-.5)*12,pz=z+(row/200-.5)*7.5,b=bandsAt(px,pz);const color=mode==='thermal'?thermalColor(temperatureAt(px,pz)):mode==='ndvi'?colorFor(normalizedDifference(b.red,b.nir)!):[Math.min(255,b.nir*480),Math.min(255,b.red*550),Math.min(255,b.red*400)];const k=(row*320+col)*4;data.data[k]=color[0];data.data[k+1]=color[1];data.data[k+2]=color[2];data.data[k+3]=255}ctx.putImageData(data,0,0)},[mode,Math.floor(time*4),scene]);
 const labels={rgb:'RGB · cámara cenital 3D',thermal:'Térmica · temperatura sintética',spectral:'Falso color · NIR / rojo / rojo',ndvi:'NDVI · (NIR − rojo) / (NIR + rojo)'};
 return <section className="sensor-console" aria-label="Visores de las cámaras"><header><strong>{local?'DRON WALL-AI':'SENTINEL-V3'}</strong><span className={flying&&playing?'rec-active':''}>{flying?(playing?'● REC SIM':'Ⅱ PAUSA'):acquired?'ARCHIVO SIM':'EN ESPERA'}</span></header><nav aria-label="Canal de cámara">{(['rgb','thermal','spectral','ndvi'] as const).map(k=><button className={mode===k?'active':''} key={k} onClick={()=>setMode(k)}>{({rgb:'RGB',thermal:'Térmica',spectral:'Espectral',ndvi:'NDVI'})[k]}</button>)}</nav><div className="sensor-frame"><canvas ref={canvas} width={320} height={200} aria-label={labels[mode]}/><span className="sensor-crosshair">+</span><span>{Math.floor(time).toString().padStart(3,'0')} s · {local?'ÁREA LOCAL':'PARCELA'}</span></div><b>{labels[mode]}</b>{mode==='thermal'?<div className="thermal-scale"><span>24 °C</span><i/><span>38 °C</span></div>:mode==='ndvi'?<div className="color-scale"><span>−1</span><i/><span>+1</span></div>:null}<p>{mode==='rgb'?'Vista renderizada del terreno bajo el dron.':mode==='thermal'?'Mismo encuadre y plantas que RGB. Temperaturas asignadas a la escena 3D; contraste visual para revisión.':mode==='spectral'?'NIR alto aparece rojo. Bandas sintéticas; no es un filtro de la imagen RGB.':'Bandas roja + NIR → índice → localizar diferencias de vigor.'}</p><button onClick={()=>{const a=document.createElement('a');a.download=`UPAIDOWN-${mode}-${Math.floor(time)}s.png`;a.href=canvas.current?.toDataURL('image/png')??'';a.click()}}>Guardar fotograma</button><small>Todos los canales son simulados. REC SIM indica adquisición narrativa; «Grabar recorrido» exporta vídeo real de la demo.</small></section>
}
