import{lazy,Suspense,type ReactNode}from'react';
import type{SimulationSnapshot}from'@ued/contracts';
import{financialModel,truth}from'@ued/configuration';
import{visualAssets}from'./visual-assets';
import{IndustrialChart,chartTheme}from'./industrial-chart';
import{formatValue}from'./formatters';
const NdviSurface3D=lazy(()=>import('./ndvi-surface-3d').then(module=>({default:module.NdviSurface3D})));

export type Classification='REAL'|'DERIVED'|'SIMULATED'|'SYNTHETIC'|'FORECAST'|'TARGET'|'SCENARIO';
export{formatValue}from'./formatters';

export function DataProvenanceBadge({kind}: {kind:Classification}){return <span className={`provenance provenance-${kind.toLowerCase()}`}>{kind}</span>}
export function KpiMetric({value,label,period,badge,context}:{value:string;label:string;period:string;badge:Classification;context?:string}){return <article className="kpi-metric"><div><strong>{value}</strong><DataProvenanceBadge kind={badge}/></div><h3>{label}</h3><p>{period}</p>{context&&<small>{context}</small>}</article>}
export function ChartLegend({items}:{items:{label:string;kind:'actual'|'forecast'|'target'|'simulated'}[]}){return <div className="chart-legend">{items.map(x=><span key={x.label}><i className={x.kind}/>{x.label}</span>)}</div>}
export function ChartTooltip({metric,value,unit,time,classification,source}:{metric:string;value:string;unit?:string;time:string;classification:Classification;source:string}){return <div className="chart-tooltip"><span>{metric}</span><strong>{value} {unit}</strong><small>{time}</small><DataProvenanceBadge kind={classification}/><small>Source · {source}</small></div>}
export function PresentationFrame({eyebrow,title,question,source,classification,children}:{eyebrow:string;title:string;question:string;source:string;classification:Classification;children:ReactNode}){return <main className="viz-page"><header className="viz-title"><div><p>{eyebrow}</p><h1>{title}</h1></div><div className="chart-meta"><DataProvenanceBadge kind={classification}/><span>Question · {question}</span><span>Source · {source}</span></div></header>{children}</main>}

export function ComparisonBar({label,value,total,note}:{label:string;value:number;total:number;note:string}){return <div className="comparison-bar"><div><b>{label}</b><span>{formatValue(value,'currency')}</span><em>{Math.round(value/total*100)}%</em></div><div className="comparison-track"><i style={{width:`${value/total*100}%`}}/></div><small>Asset created · {note}</small></div>}
export function FinancialBridge(){return <section className="empty-chart"><span>REVENUE & EBITDA DEVELOPMENT</span><h2>MODEL INPUTS PENDING APPROVAL</h2><p>No approved monthly revenue, recurring revenue, COGS or EBITDA series exists. No curve is rendered.</p><DataProvenanceBadge kind="TARGET"/></section>}
const modelScenarios=financialModel.scenarios;
const baseScenario=modelScenarios.find(x=>x.id==='BASE')!;
const envelopeEntries=[
  ['Minimum viable',truth.financial.provisional_capital_envelopes.minimum_viable],
  ['Recommended',truth.financial.provisional_capital_envelopes.recommended],
  ['Comfortable',truth.financial.provisional_capital_envelopes.comfortable],
]as const;
const assetNotes:Record<string,string>={Team:'Execution capacity','Software & cloud':'Operational software environment','AI & data':'Versioned data and experiments',Sentinel:'Instrumented fixed-node iteration','Rover platform':'Commercial mobility base','Rover integration':'Integrated field rover prototype',Drone:'Selected aerial integration path','Field validation':'Reproducible field evidence','China sourcing':'Supplier shortlist and quotes','IP / legal':'Corporate and IP baseline',Regulatory:'Operating constraints','Investor & commercial validation':'Validated commercial inputs'};
const baseAllocations=Object.entries(baseScenario.months.reduce<Record<string,number>>((totals,month)=>{for(const[category,value]of Object.entries(month.by_category))totals[category]=(totals[category]??0)+value;return totals},{})).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]);
export function ScenarioMatrix(){return <section className="scenario-envelope" aria-label="Provisional capital envelopes"><div className="panel-head"><div><span>CAPITAL ENVELOPES</span><h2>Decision range, not an approved ask</h2></div><DataProvenanceBadge kind="SCENARIO"/></div>{envelopeEntries.map(([label,item])=><article key={label}><div><b>{label}</b><strong>{formatValue(item.amount,'currency')}</strong></div><p>{item.basis}</p><small>{item.status} · Current round terms remain null</small></article>)}</section>}
export function MilestoneTimeline(){const items=[['M0','Corporate + IP','PLANNED'],['M3','Rover sourcing','PLANNED'],['M6','Data pipeline','DEPENDENT'],['M9','Field evidence','DEPENDENT'],['M12','Repeatable offer','DEPENDENT']];return <section className="milestone-timeline">{items.map(([m,t,s])=><article key={m}><time>{m}</time><i/><h3>{t}</h3><DataProvenanceBadge kind="SCENARIO"/><small>{s}</small></article>)}</section>}
export function InvestorFinancialView(){const baseTotal=baseScenario.total_m0_m15;const runway=truth.financial.provisional_capital_envelopes.recommended.amount/baseScenario.average_monthly_burn_m1_m15;return <PresentationFrame eyebrow="INVESTOR · CAPITAL EFFICIENCY" title="Capital should create defensible assets" question="What can each provisional capital envelope create?" source="financial/model-v1.json + canonical truth" classification="SCENARIO"><section className="kpi-row"><KpiMetric value={formatValue(truth.financial.provisional_capital_envelopes.recommended.amount,'currency')} label="Base planning reference" period="M0–M15 + 10% contingency" badge="SCENARIO" context="Not an approved ask"/><KpiMetric value={`${runway.toFixed(1)} months`} label="Scenario runway" period="Recommended envelope ÷ Base average burn" badge="SCENARIO" context="Formula-driven; not approved"/><KpiMetric value="€500K" label="12-month EBITDA target" period="TARGET_TO_VALIDATE" badge="TARGET" context="Blocked by price, volume, COGS, margin and timing"/></section><section className="viz-grid investor-grid"><article className="panel funds-panel"><div className="panel-head"><div><span>BASE USE OF FUNDS → ASSETS</span><h2>€806.9K before contingency</h2></div><DataProvenanceBadge kind="SCENARIO"/></div><p className="chart-caption">Provisional Base planning allocation across M0–M15. Every amount remains subject to quotes, validation or management approval.</p><div className="fund-bars">{baseAllocations.map(([label,value])=><ComparisonBar key={label} label={label} value={value} total={baseTotal} note={assetNotes[label]??'Evidence milestone'}/>)}</div></article><article className="panel value-panel"><div className="panel-head"><div><span>CAPITAL → VALUE CREATION</span><h2>Evidence compounds value</h2></div></div><div className="value-chain-viz">{[['CAPITAL','Scenario envelope'],['BUILD','Rover + Sentinel'],['VALIDATE','Field evidence'],['DATA','Structured observations'],['IP','Models + know-how'],['RECURRENCE','Commercial inputs'],['POSITION','Next financing']].map(([a,b],i)=><div key={a}><b>{String(i+1).padStart(2,'0')}</b><span>{a}<small>{b}</small></span></div>)}</div></article><article className="panel wide"><div className="panel-head"><div><span>12-MONTH VALUE CREATION</span><h2>Evidence gates</h2></div></div><MilestoneTimeline/></article><ScenarioMatrix/><section className="empty-chart"><span>ROUND STRUCTURE</span><h2>UNDER FINAL REVIEW</h2><p>Ask, instrument, pre-money, post-money and dilution remain null. The three envelopes are planning outputs, not active terms.</p><DataProvenanceBadge kind="TARGET"/></section><FinancialBridge/></section></PresentationFrame>}

const ndviBins=[2,4,7,12,21,32,46,39,25,9];
export function DistributionChart(){return <IndustrialChart className="distribution-chart" label="Synthetic NDVI distribution histogram" option={{backgroundColor:'transparent',grid:{left:34,right:8,top:14,bottom:28},tooltip:{trigger:'axis',backgroundColor:'#13231e',borderColor:chartTheme.grid,textStyle:{color:chartTheme.text,fontSize:10},formatter:(p:unknown)=>{const item=(p as Array<{axisValue:string;value:number}>)[0];return item?`NDVI ${item.axisValue}<br/><b>${item.value} cells</b>`:''}},xAxis:{type:'category',data:['-1.0','-.8','-.6','-.4','-.2','0','.2','.4','.6','.8'],axisLine:{lineStyle:{color:chartTheme.grid}},axisTick:{show:false},axisLabel:{color:chartTheme.muted,fontSize:8}},yAxis:{type:'value',axisLine:{show:false},axisTick:{show:false},splitLine:{lineStyle:{color:chartTheme.grid}},axisLabel:{color:chartTheme.muted,fontSize:8}},series:[{type:'bar',data:ndviBins,itemStyle:{color:chartTheme.mint,borderRadius:[2,2,0,0]},emphasis:{itemStyle:{color:chartTheme.lime}},barMaxWidth:24}]}}/>}
export function NdviAnalytics(){return <PresentationFrame eyebrow="ANALYTICS · NDVI" title="Vegetation condition, spatially first" question="Where is vegetation performance deviating?" source="data/ndvi/ndvi-demo.json" classification="SYNTHETIC"><section className="ndvi-layout"><article className="ndvi-raster"><Suspense fallback={<div className="raster-surface"><div className="raster-anomaly"/><span>LOADING WEBGL SURFACE</span></div>}><NdviSurface3D/></Suspense><div className="ndvi-legend"><span>-1.0</span><i/><span>0</span><i/><span>1.0</span></div><DataProvenanceBadge kind="SYNTHETIC"/></article><aside className="panel ndvi-summary"><div className="panel-head"><div><span>DISTRIBUTION</span><h2>Mission snapshot</h2></div></div><div className="stat-grid"><KpiMetric value="0.61" label="Mean NDVI" period="Mission 001" badge="SYNTHETIC"/><KpiMetric value="0.65" label="Median" period="Mission 001" badge="SYNTHETIC"/><KpiMetric value="0.34" label="P10" period="Mission 001" badge="SYNTHETIC"/><KpiMetric value="0.81" label="P90" period="Mission 001" badge="SYNTHETIC"/></div><DistributionChart/><p className="chart-caption">Exact values from the declared synthetic fallback. No historical comparison is available.</p></aside></section></PresentationFrame>}

export function AnomalyView(){return <PresentationFrame eyebrow="MISSION INTELLIGENCE" title="Localized vegetation anomaly" question="Where should the system inspect next, and why?" source="Deterministic simulation engine" classification="SIMULATED"><section className="evidence-layout"><article className="panel location-panel"><span>WHERE</span><h2>Simulated target</h2><strong>AREA NOT QUANTIFIED</strong><div className="mini-field"><i/></div></article><article className="panel"><span>WHAT</span><h2>Anomaly event detected</h2><div className="delta-row"><b>NDVI</b><strong>READY</strong><small>Synthetic fallback available</small></div><div className="delta-row"><b>Confidence</b><strong>NOT SCORED</strong><small>No approved model output</small></div></article><article className="panel"><span>WHY</span><h2>Evidence required</h2><ul className="evidence-list"><li><i style={{width:'100%'}}/>Synthetic NDVI signal</li><li><i style={{width:'0%'}}/>Ground observation pending</li><li><i style={{width:'0%'}}/>Soil sample pending</li></ul></article><article className="panel action-panel"><span>NEXT ACTION</span><h2>Ground inspection</h2><p>Dispatch ROVER_001 to validate the simulated aerial signal before any agronomic interpretation.</p><DataProvenanceBadge kind="SIMULATED"/></article></section></PresentationFrame>}

export function GroundTruthView(){return <PresentationFrame eyebrow="ROVER_001 · GROUND TRUTH" title="From aerial signal to physical evidence" question="Does local evidence support the aerial anomaly?" source="Deterministic scenario telemetry" classification="SYNTHETIC"><section className="ground-flow"><article><span>AERIAL SIGNAL</span><b>NDVI ready</b><small>Synthetic fallback</small></article><i>→</i><article><span>GROUND OBSERVATION</span><b>Inspection event</b><small>No quantified camera inference</small></article><i>→</i><article><span>SOIL SAMPLE</span><b>28.4% moisture</b><small>pH 6.7 · EC 1.31 dS/m</small></article></section><div className="reading-note"><DataProvenanceBadge kind="SYNTHETIC"/><p>DEMO READING · No calibration, sensor accuracy or agronomic diagnosis is implied.</p></div></PresentationFrame>}

export function DataEngineView(){const inputs=['AERIAL IMAGERY','SPECTRAL RASTERS','FIELD TELEMETRY','GROUND IMAGERY','SOIL READINGS','GEOSPATIAL CONTEXT'];const outputs=['VEGETATION MAPS','ANOMALY QUEUE','TEMPORAL MEMORY','MISSION RECOMMENDATIONS','AGRONOMIC REPORTS','TRAINING DATASET'];return <PresentationFrame eyebrow="DATA & AI ENGINE" title="Hardware captures reality. Data creates memory." question="How can deployment create durable data value?" source="Product thesis · not a production architecture claim" classification="SCENARIO"><section className="data-engine-cinematic"><div className="engine-inputs"><p>FIELD INPUTS</p>{inputs.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div><figure><img src={visualAssets.DATA_ENGINE?.src} alt="Conceptual geospatial data architecture"/><figcaption>CONCEPT DATA VISUAL · ARCHITECTURE TO VALIDATE</figcaption></figure><div className="engine-outputs"><p>INTELLIGENCE OUTPUTS</p>{outputs.map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div></section><section className="value-conversion"><span>HARDWARE <b>→ DATA</b></span><span>DATA <b>→ MEMORY</b></span><span>MEMORY <b>→ MODELS</b></span><span>MODELS <b>→ DECISIONS</b></span></section></PresentationFrame>}

export function SystemHealthView({connected}:{connected:boolean}){const services=[['API','HEALTHY','LOCAL CHECK'],['WebSocket',connected?'HEALTHY':'RECONNECTING',connected?'CONNECTED':'—'],['Gateway','HEALTHY','LOCAL'],['Simulation','READY','DETERMINISTIC'],['Worker','DEMO MODE','SIMULATED'],['Database','DEMO MODE','NOT ACTIVE PERSISTENCE']];return <PresentationFrame eyebrow="OPERATOR · SYSTEM HEALTH" title="Runtime status without decorative gauges" question="Can the meeting runtime serve the demo now?" source="Local runtime health and WebSocket state" classification="SIMULATED"><section className="health-table"><div><b>Service</b><b>Status</b><b>Mode / observation</b></div>{services.map(([a,b,c])=><div key={a}><strong>{a}</strong><span className={b==='HEALTHY'?'healthy':'mode'}><i/>{b}</span><em>{c}</em></div>)}</section><p className="health-note">No production SLA or fabricated latency is shown. Runtime mode remains explicitly DEMO.</p></PresentationFrame>}

export function ReportView(){return <PresentationFrame eyebrow="REPORT · MISSION 001" title="Evidence package ready for human review" question="What did this simulated mission establish?" source="Deterministic scenario output" classification="SIMULATED"><section className="report-grid"><KpiMetric value="100%" label="Survey coverage" period="Mission 001" badge="SIMULATED"/><KpiMetric value="1" label="Anomaly flagged" period="Mission 001" badge="SIMULATED"/><KpiMetric value="1" label="Ground sample" period="Mission 001" badge="SYNTHETIC"/><KpiMetric value="READY" label="Evidence package" period="Human review required" badge="SIMULATED"/></section><section className="panel report-conclusion"><span>GENERATED INSIGHT</span><h2>A localized aerial deviation was inspected by the rover and paired with a synthetic soil reading.</h2><p>This demo establishes workflow coherence, not agronomic validity or field performance.</p></section></PresentationFrame>}
