import{Canvas,useFrame}from'@react-three/fiber';
import{OrbitControls}from'@react-three/drei';
import{Suspense,useRef}from'react';
import type{Group}from'three';
import type{SimulationSnapshot}from'@ued/contracts';

const dark='#151b1a',white='#d9ddda',metal='#7d8581',green='#27362b',rubber='#090b0b',signal='#b9f36a';
function Track({x}:{x:number}){return <group position={[x,.48,0]}><mesh castShadow><boxGeometry args={[.42,.65,2.25]}/><meshStandardMaterial color={rubber} roughness={.9}/></mesh><mesh position={[x>0?-.215:.215,0,0]}><boxGeometry args={[.035,.48,1.72]}/><meshStandardMaterial color={white} metalness={.45} roughness={.35}/></mesh></group>}
function Rover3D({probing=false}:{probing?:boolean}){return <group position={[-2.25,0,1.2]} rotation={[0,.38,0]}><Track x={-1}/><Track x={1}/><mesh position={[0,.72,0]} castShadow><boxGeometry args={[1.65,.62,2.1]}/><meshStandardMaterial color={white} metalness={.45} roughness={.3}/></mesh><mesh position={[0,1.32,0]} castShadow><boxGeometry args={[2.05,.78,2.45]}/><meshStandardMaterial color={dark} metalness={.5} roughness={.28}/></mesh><mesh position={[0,1.66,0]}><boxGeometry args={[1.55,.12,1.75]}/><meshStandardMaterial color="#292f2d"/></mesh><group position={[0,1.25,-1.28]}>{[-.62,-.32,.32,.62].map(x=><mesh key={x} position={[x,0,0]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.1,.1,.08,20]}/><meshStandardMaterial color={x<0?signal:'#7b8d86'} emissive={x<0?signal:'#000'} emissiveIntensity={.18}/></mesh>)}</group><group position={[0,probing?.15:.95,-1.5]}><mesh><cylinderGeometry args={[.11,.11,1.2,18]}/><meshStandardMaterial color={metal} metalness={.8}/></mesh><mesh position={[0,-.65,0]}><cylinderGeometry args={[.2,.14,.16,18]}/><meshStandardMaterial color={metal} metalness={.8}/></mesh></group><mesh position={[.82,2.05,.65]}><cylinderGeometry args={[.025,.025,1.25,10]}/><meshStandardMaterial color={dark}/></mesh></group>}
function Sentinel3D({height=1,bayOpen=false}:{height?:number;bayOpen?:boolean}){const mast=2.2+height*2.2;return <group position={[2.5,0,-.4]}><mesh position={[0,.12,0]} receiveShadow><boxGeometry args={[2.1,.24,1.7]}/><meshStandardMaterial color="#77736b" roughness={.95}/></mesh><mesh position={[0,.55,0]}><boxGeometry args={[.85,.75,.75]}/><meshStandardMaterial color={green} roughness={.55}/></mesh>{[-.22,0,.22].map(x=><mesh key={x} position={[x,mast/2+.45,0]}><cylinderGeometry args={[.07,.085,mast,16]}/><meshStandardMaterial color={metal} metalness={.8} roughness={.25}/></mesh>)}<group position={[0,mast+.75,0]}><mesh castShadow><boxGeometry args={[1.75,.8,1.25]}/><meshStandardMaterial color={green} roughness={.5}/></mesh><mesh position={[0,.58,.42]} rotation={[bayOpen?-.85:0,0,0]}><boxGeometry args={[1.7,.12,1.2]}/><meshStandardMaterial color={dark} metalness={.35}/></mesh><mesh position={[.68,1.25,0]}><cylinderGeometry args={[.025,.025,1.7,10]}/><meshStandardMaterial color={dark}/></mesh><mesh position={[0,1.1,0]}><cylinderGeometry args={[.14,.18,.7,18]}/><meshStandardMaterial color={metal} metalness={.75}/></mesh></group></group>}
function Drone3D({active=false}:{active?:boolean}){const ref=useRef<Group>(null);useFrame(({clock})=>{if(ref.current&&active){ref.current.position.y=5.5+Math.sin(clock.elapsedTime*1.5)*.16;ref.current.rotation.y=clock.elapsedTime*.12}});return <group ref={ref} position={[.7,active?5.5:3.8,-1.1]} scale={.55}><mesh><boxGeometry args={[1,.22,.65]}/><meshStandardMaterial color={white} metalness={.35}/></mesh>{[[-.8,0,-.55],[.8,0,-.55],[-.8,0,.55],[.8,0,.55]].map((p,i)=><group key={i} position={p as[number,number,number]}><mesh><boxGeometry args={[1.2,.08,.1]}/><meshStandardMaterial color={dark}/></mesh><mesh position={[i%2?-.42:.42,.07,0]}><cylinderGeometry args={[.48,.48,.035,24]}/><meshStandardMaterial color="#202624" transparent opacity={.62}/></mesh></group>)}</group>}
function Field({snapshot}:{snapshot:SimulationSnapshot}){const active=['LAUNCH','FLIGHT','CAPTURE','NDVI','ANOMALY'].includes(snapshot.phase);const probing=snapshot.phase==='PROBE';const mastActor=snapshot.actors.find(a=>a.type==='mast');const height=Number(mastActor?.telemetry.heightPercent??0)/100;return <><color attach="background" args={['#8ba0a5']}/><fog attach="fog" args={['#8ba0a5',12,28]}/><ambientLight intensity={1.1}/><directionalLight position={[-6,10,-4]} intensity={2.4} castShadow shadow-mapSize={[1024,1024]}/><mesh rotation={[-Math.PI/2,0,0]} receiveShadow><planeGeometry args={[42,42,32,32]}/><meshStandardMaterial color="#302b20" roughness={1}/></mesh>{[-7,-4,4,7].map(z=><mesh key={z} position={[0,.14,z]} receiveShadow><boxGeometry args={[28,.22,.72]}/><meshStandardMaterial color="#405a2d" roughness={1}/></mesh>)}<Rover3D probing={probing}/><Sentinel3D height={height} bayOpen={Boolean(mastActor?.telemetry.bayOpen)}/><Drone3D active={active}/></>}
export function FieldScene3D({snapshot}:{snapshot:SimulationSnapshot}){return <section className="field-scene-3d" aria-label="Interactive 3D concept scene"><div className="field-scene-fallback"/><Suspense fallback={null}><Canvas shadows camera={{position:[8,7,11],fov:42}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}}><Field snapshot={snapshot}/><OrbitControls enablePan={false} minDistance={8} maxDistance={20} maxPolarAngle={Math.PI/2.08} target={[0,1.3,0]}/></Canvas></Suspense><div className="scene-classification"><b>INTERACTIVE 3D CONCEPT SCENE</b><span>PROCEDURAL PLACEHOLDER GEOMETRY · GLB READY</span></div></section>}
