import{Canvas}from'@react-three/fiber';
import{OrbitControls}from'@react-three/drei';
import{useMemo}from'react';
import{BufferAttribute,BufferGeometry,Color,DoubleSide}from'three';

function ndviValue(x:number,z:number){const base=.68+.11*Math.sin(x*.58)+.07*Math.cos(z*.72);const anomaly=.58*Math.exp(-((x-2.1)**2+(z+.4)**2)/3.2);const edge=.05*Math.sin((x+z)*1.7);return Math.max(-1,Math.min(1,base-anomaly+edge))}
function ndviColor(value:number){const stops=[[-1,'#7b3d34'],[-.25,'#bd7535'],[0,'#c8a742'],[.35,'#8b9b3e'],[.65,'#3d7a45'],[1,'#12613e']]as const;for(let i=1;i<stops.length;i++){if(value<=stops[i]![0]){const[a,ca]=stops[i-1]!,[b,cb]=stops[i]!;return new Color(ca).lerp(new Color(cb),(value-a)/(b-a))}}return new Color(stops.at(-1)![1])}
function Surface(){const geometry=useMemo(()=>{const width=12,depth=8,cols=72,rows=48,positions:number[]=[],colors:number[]=[],indices:number[]=[];for(let row=0;row<=rows;row++)for(let col=0;col<=cols;col++){const x=col/cols*width-width/2,z=row/rows*depth-depth/2,v=ndviValue(x,z),y=.18+(v+1)*.42;positions.push(x,y,z);const c=ndviColor(v);colors.push(c.r,c.g,c.b)}for(let row=0;row<rows;row++)for(let col=0;col<cols;col++){const a=row*(cols+1)+col,b=a+1,c=a+cols+1,d=c+1;indices.push(a,c,b,b,c,d)}const g=new BufferGeometry();g.setAttribute('position',new BufferAttribute(new Float32Array(positions),3));g.setAttribute('color',new BufferAttribute(new Float32Array(colors),3));g.setIndex(indices);g.computeVertexNormals();return g},[]);return <group rotation={[0,-.18,0]}><mesh geometry={geometry} receiveShadow castShadow><meshStandardMaterial vertexColors side={DoubleSide} roughness={.76} metalness={0}/></mesh><mesh geometry={geometry} position={[0,.015,0]}><meshBasicMaterial color="#dbe8df" wireframe transparent opacity={.075}/></mesh><mesh position={[2.1,.95,-.4]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.8,.035,12,64]}/><meshBasicMaterial color="#f07b68" transparent opacity={.9}/></mesh></group>}
export function NdviSurface3D(){return <div className="ndvi-webgl" role="img" aria-label="Interactive synthetic NDVI surface"><Canvas camera={{position:[8,7,10],fov:38}} dpr={[1,1.5]} gl={{antialias:true,powerPreference:'high-performance'}}><color attach="background" args={['#07100f']}/><fog attach="fog" args={['#07100f',13,24]}/><ambientLight intensity={1.4}/><directionalLight position={[-4,8,5]} intensity={2.2}/><Surface/><gridHelper args={[18,18,'#294039','#182923']} position={[0,0,0]}/><OrbitControls enablePan={false} minDistance={8} maxDistance={18} maxPolarAngle={Math.PI/2.15} target={[0,.3,0]}/></Canvas><div className="ndvi-3d-controls"><b>INTERACTIVE WEBGL SURFACE</b><span>DRAG TO ORBIT · SCROLL TO ZOOM</span></div></div>}
