import{type ReactNode,useState}from'react';
import{DataProvenanceBadge}from'./data-viz';
import{visualAssets}from'./visual-assets';
import{motion}from'motion/react';

const roverAnatomy=[['PERCEPTION','Front RGB, spectral and depth concepts'],['SOIL PROBE','Retractable ground-truth mechanism'],['DRONE BAY','Protected docking architecture'],['COMMUNICATIONS','External field connectivity concept'],['EDGE COMPUTE','Onboard mission and sensor processing'],['MOBILITY','Commercial tracked platform candidate']]as const;
const roverStates=[['IDLE','ROVER_FRONT'],['MOVING','ROVER_SIDE'],['ARRIVED','ROVER_FRONT'],['PROBE','ROVER_PROBE'],['DRONE','ROVER_DOCK_OPEN'],['RETURN','ROVER_REAR']]as const;
const sentinelStates=[['STOWED','Lower operating position'],['RAISING','Mechanical elevation in progress'],['DEPLOYED','Upper carriage deployed'],['BAY OPEN','Dock accessible'],['DRONE LAUNCH','Aerial layer departing']]as const;

function ProductFrame({kind,title,role,children}:{kind:string;title:string;role:string;children:ReactNode}){return <motion.main className="product-page" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.8,ease:[.2,.75,.15,1]}}><section className="product-hero-copy"><p>{kind} · PRODUCT EXPERIENCE</p><h1>{title}</h1><h2>{role}</h2><div><DataProvenanceBadge kind="SCENARIO"/><span>CONCEPT RENDER · NOT PHYSICAL PROTOTYPE</span></div></section>{children}</motion.main>}

export function RoverProductExperience(){const[hotspot,setHotspot]=useState(0);const[state,setState]=useState(0);const selected=roverStates[state]!;return <ProductFrame kind="ROVER_001" title="Autonomous mobile field node" role="Ground investigation where aerial signals need proof"><section className="product-visual product-visual-rover"><div className="depth-grid"/><img src={visualAssets.ROVER_FRONT?.src} alt="ROVER_001 industrial concept render"/><div className="product-orbit"><span>RGB</span><span>SPECTRAL</span><span>SOIL</span><span>TELEMETRY</span><span>POSITION</span></div></section><section className="product-section anatomy-section"><header><p>SYSTEM ANATOMY</p><h2>One platform, six evidence systems</h2></header><div className="anatomy-stage"><img src={visualAssets.ROVER_EXPLODED?.src} alt="Exploded Rover engineering concept"/><nav aria-label="Rover anatomy">{roverAnatomy.map(([name],i)=><button key={name} className={i===hotspot?'active':''} onMouseEnter={()=>setHotspot(i)} onFocus={()=>setHotspot(i)} onClick={()=>setHotspot(i)}>{String(i+1).padStart(2,'0')} · {name}</button>)}</nav><aside><b>{roverAnatomy[hotspot]?.[0]}</b><p>{roverAnatomy[hotspot]?.[1]}</p><small>CONCEPT ARCHITECTURE · CONFIGURATION TO VALIDATE</small></aside></div></section><section className="product-section state-section"><header><p>MISSION STATES</p><h2>State → change → result</h2></header><div className="state-stage"><img key={selected[1]} src={visualAssets[selected[1]]?.src} alt={`Rover concept state ${selected[0]}`}/><div><b>{selected[0]}</b><p>{state<3?'Positioning for evidence capture':state===3?'Physical soil measurement concept':state===4?'Aerial layer handoff concept':'Returning to mission readiness'}</p></div></div><nav className="state-nav">{roverStates.map(([name],i)=><button key={name} className={i===state?'active':''} onClick={()=>setState(i)}><span>{String(i+1).padStart(2,'0')}</span>{name}</button>)}</nav></section><section className="data-convergence"><div><b>RGB</b><b>SPECTRAL</b><b>SOIL</b><b>TELEMETRY</b><b>POSITION</b></div><i>→</i><strong>DATA ENGINE</strong><p>Every observation retains place, time and provenance.</p></section></ProductFrame>}

export function SentinelProductExperience(){const[state,setState]=useState(0);return <ProductFrame kind="SENTINEL" title="Autonomous fixed field node" role="Persistent presence, aerial readiness and environmental context"><section className="sentinel-hero"><div className="sentinel-image-window"><img src={visualAssets.SENTINEL_MASTER?.src} alt="Sentinel master concept board"/></div><aside><span>FIXED SENSING</span><span>MECHANICAL DEPLOYMENT</span><span>AERIAL DOCKING</span><span>ENVIRONMENTAL CONTEXT</span><p>No height, energy, drone model or communications specification is asserted.</p></aside></section><section className="product-section sentinel-sequence"><header><p>DEPLOYMENT SEQUENCE</p><h2>From protected node to aerial mission</h2></header><div className="sequence-window" data-state={state}><img src={visualAssets.SENTINEL_SEQUENCE?.src} alt="Sentinel deployment animation reference"/><div><b>{sentinelStates[state]?.[0]}</b><p>{sentinelStates[state]?.[1]}</p></div></div><nav className="state-nav">{sentinelStates.map(([name],i)=><button key={name} className={i===state?'active':''} onClick={()=>setState(i)}><span>{String(i+1).padStart(2,'0')}</span>{name}</button>)}</nav><p className="product-disclosure">Deployment images are animation references. Current Sentinel configuration remains `PRODUCT DECISION PENDING`.</p></section></ProductFrame>}

export function FleetExperience(){return <main className="fleet-experience"><section className="fleet-hero"><img src={visualAssets.SYSTEM_HERO?.src} alt="UP-EYE-DAWN ecosystem concept"/><div><p>AUTONOMOUS FIELD INTELLIGENCE</p><h1>Fixed presence.<br/>Aerial context.<br/>Ground truth.</h1><span>CONCEPT RENDER · SYSTEM VISION</span></div></section><section className="fleet-products"><a href="/demo/fleet/sentinel/sentinel-001"><small>FIXED NODE</small><h2>SENTINEL</h2><p>Persistent field context and autonomous aerial readiness.</p><b>EXPLORE PRODUCT →</b></a><a href="/demo/fleet/rover/rover-001"><small>MOBILE NODE</small><h2>ROVER_001</h2><p>Autonomous investigation and soil ground truth.</p><b>EXPLORE PRODUCT →</b></a></section></main>}
