import type {ActorSnapshot,DomainEvent,Scenario,SimulationSnapshot} from '@ued/contracts';
const route:[number,number][]= [[-3.7018,37.1920],[-3.7008,37.1931],[-3.6995,37.1932],[-3.6985,37.1924],[-3.6992,37.1914],[-3.7007,37.1912],[-3.7018,37.1920]];
const roverRoute:[number,number][]= [[-3.7015,37.1913],[-3.7008,37.1917],[-3.7001,37.1920],[-3.6994,37.1922]];
const lerp=(a:number,b:number,t:number)=>a+(b-a)*t;
function onPath(path:[number,number][],progress:number):[number,number]{const p=Math.max(0,Math.min(.999999,progress))*(path.length-1);const i=Math.floor(p);const t=p-i;const a=path[i]??path[0]!;const b=path[i+1]??a;return[lerp(a[0],b[0],t),lerp(a[1],b[1],t)]}
const phaseAt=(t:number)=>t<20?'PREPARE':t<60?'SENTINEL':t<85?'LAUNCH':t<190?'FLIGHT':t<215?'CAPTURE':t<255?'NDVI':t<280?'ANOMALY':t<350?'ROVER':t<380?'PROBE':t<410?'FUSION':'REPORT';
export class SimulationEngine{
 private t=0;private seq=0;private speed=1;private status:SimulationSnapshot['status']='READY';private events:DomainEvent[]=[];
 constructor(public readonly scenario:Scenario,public readonly runId='run_new_york_001'){}
 command(action:string,value?:number){if(action==='RESET'){this.t=0;this.seq=0;this.speed=1;this.events=[];this.status='READY';return this.snapshot()}if(action==='PLAY'||action==='RESUME')this.status='RUNNING';if(action==='PAUSE')this.status='PAUSED';if(action==='SET_SPEED'&&[1,2,5,10,20].includes(value??0))this.speed=value!;if(action==='SEEK')this.t=Math.max(0,Math.min(this.scenario.durationSeconds,value??0));this.emit(`simulation.${action.toLowerCase()}`,'simulation',{});return this.snapshot()}
 tick(realDelta:number){if(this.status!=='RUNNING')return this.snapshot();const before=phaseAt(this.t);this.t=Math.min(this.scenario.durationSeconds,this.t+realDelta*this.speed);const after=phaseAt(this.t);if(before!==after)this.emit('device.state.changed','simulation',{from:before,to:after});if(this.t>=this.scenario.durationSeconds){this.status='COMPLETED';this.emit('simulation.completed','simulation',{})}return this.snapshot()}
 snapshot():SimulationSnapshot{const phase=phaseAt(this.t);const flight=Math.max(0,Math.min(1,(this.t-85)/130));const rover=Math.max(0,Math.min(1,(this.t-280)/70));const mastHeight=this.t<20?0:this.t<60?((this.t-20)/40)*100:this.t<410?100:0;const droneState=this.t<60?'DOCKED':this.t<85?'PREFLIGHT':this.t<190?'EN_ROUTE':this.t<215?'CAPTURING':this.t<280?'RETURNING':'DOCKED';const roverState=this.t<280?'IDLE':this.t<350?'MOVING':this.t<380?'PROBING':'ARRIVED';const actors:ActorSnapshot[]=[{id:'sentinel-001',type:'mast',state:mastHeight>99?'DEPLOYED':mastHeight>0?'RAISING':'STOWED',position:[-3.7018,37.192],battery:92-Math.min(8,this.t/55),telemetry:{heightPercent:+mastHeight.toFixed(1),solarWatts:640,windMps:3.8,bayOpen:this.t>55&&this.t<280}},{id:'drone-001',type:'drone',state:droneState,position:onPath(route,flight),battery:+Math.max(48,98-flight*45).toFixed(1),telemetry:{altitude:droneState==='EN_ROUTE'?42:0,speed:droneState==='EN_ROUTE'?8.4:0,signal:+(100-flight*18).toFixed(1),waypoint:Math.floor(flight*12)+1}},{id:'rover-001',type:'rover',state:roverState,position:onPath(roverRoute,rover),battery:+Math.max(72,96-rover*18).toFixed(1),telemetry:{speed:roverState==='MOVING'?1.4:0,signal:+(96-rover*7).toFixed(1),probe:roverState==='PROBING'?'DEPLOYED':'RETRACTED'}},{id:'probe-001',type:'probe',state:roverState==='PROBING'?'READING':'RETRACTED',position:onPath(roverRoute,1),battery:100,telemetry:{moisture:28.4,temperature:21.7,ec:1.31,ph:6.7,N:42,P:25,K:118}},{id:'analytics-001',type:'analytics',state:this.t<215?'IDLE':this.t<255?'GENERATING_NDVI':this.t<410?'READY':'GENERATING_REPORT',position:[-3.7,37.192],battery:100,telemetry:{progress:Math.max(0,Math.min(100,(this.t-215)/.4))}}];return{runId:this.runId,scenarioId:this.scenario.id,sequence:this.seq,simulationTime:+this.t.toFixed(2),speed:this.speed,status:this.status,phase,actors,coverage:+Math.max(0,Math.min(100,flight*100)).toFixed(1),ndviReady:this.t>=215,anomalyReady:this.t>=255,reportReady:this.t>=410}}
 eventLog(){return [...this.events]}
 private emit(eventType:string,source:string,payload:Record<string,unknown>){this.seq+=1;this.events.push({eventId:`evt_${String(this.seq).padStart(5,'0')}`,eventType,eventVersion:1,sequence:this.seq,runId:this.runId,scenarioId:this.scenario.id,source,correlationId:'mission_001',causationId:`cmd_${this.seq}`,recordedAt:new Date(Date.UTC(2026,7,16,0,0,0)+this.t*1000).toISOString(),simulationTime:+this.t.toFixed(2),classification:'SIMULATED',payload})}
}
