import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
import{postMoney,investorOwnership,inversePreMoney,currentShareholderRetention,runwayMonths,scenarioCoverage}from'./round-decision-core.mjs';
const decision=JSON.parse(fs.readFileSync(new URL('../financial/round-decision-v1.json',import.meta.url),'utf8'));
test('post-money and dilution reconcile',()=>{for(const row of decision.valuation.dilution_table)for(const ticket of decision.main_tickets){const d=row[String(ticket)];assert.equal(postMoney(ticket,row.pre_money),ticket+row.pre_money);assert.ok(Math.abs(d-investorOwnership(ticket,row.pre_money))<1e-12)}});
test('inverse pre-money produces requested ownership',()=>{for(const row of decision.valuation.inverse_pre_money_table)for(const ticket of decision.main_tickets){const pre=row[String(ticket)];assert.ok(Math.abs(investorOwnership(ticket,pre)-row.max_dilution)<1e-12)}});
test('future dilution and option pool are multiplicative and separate',()=>{for(const row of decision.valuation.cumulative_dilution){const expected=currentShareholderRetention(row.investment,row.pre_money,row.future_dilution,row.option_pool);assert.ok(Math.abs(expected-row.current_shareholders_after_current_future_and_pool)<1e-12)}});
test('scenario coverage and runway match ticket table',()=>{for(const row of decision.capital_table){const source=row.comparison==='LEAN'?464007.6:row.comparison==='BASE'?887628.5:1655375.55;const burn=row.comparison==='LEAN'?28794.133333333335:row.comparison==='BASE'?52462.333333333336:93297.13333333333;assert.ok(Math.abs(row.coverage-scenarioCoverage(row.capital,source))<1e-9);assert.ok(Math.abs(row.runway-runwayMonths(row.capital,burn))<1e-9)}});
test('capital envelopes and statuses are controlled',()=>{assert.deepEqual(decision.main_tickets,[500000,750000,1000000,1500000]);for(const row of decision.capital_table)for(const key of['sentinel','rover','ai_data','field_pilots','team','china','legal_ip','buffer'])assert.ok(decision.allowed_statuses.includes(row[key]));assert.equal(decision.status,'AWAITING_FOUNDER_APPROVAL')});
test('recommendation respects floor and dilution guardrail',()=>{const r=decision.recommendation;assert.ok(investorOwnership(r.target_close,r.valuation_floor)<=r.maximum_dilution+1e-12);assert.equal(r.classification,'CODEX RECOMMENDATION — NOT FOUNDER APPROVED')});
