import{readFile,readdir,stat}from'node:fs/promises';
import{resolve,relative,extname}from'node:path';
import process from'node:process';
const root=resolve(import.meta.dirname,'..'),workspace=resolve(root,'..');
const truth=JSON.parse(await readFile(resolve(root,'source-of-truth/new-york-2026.json'),'utf8'));
const failures=[],pass=(condition,message)=>{if(!condition)failures.push(message)};
pass(truth.company.legal_name==='UP AI DOWN SL','company legal name must remain UP AI DOWN SL');pass(truth.company.country==='Spain','company country must remain Spain');pass(truth.company.stage==='Early-stage / pre-industrialization','company stage changed unexpectedly');pass(truth.terminology.rover==='ROVER_001','canonical rover must be ROVER_001');pass(truth.terminology.drone==='AUTONOMOUS DRONE LAYER','canonical drone terminology changed');
for(const product of truth.products)pass(truth.allowed_maturity.includes(product.maturity),`invalid maturity ${product.maturity} on ${product.id}`);for(const key of['current_ask','instrument','pre_money','post_money','dilution'])pass(truth.round[key]===null,`round.${key} must remain null until approved`);pass(truth.proposed_round_decision?.status==='AWAITING_FOUNDER_APPROVAL','proposed round must await explicit founder approval');pass(truth.proposed_round_decision?.classification==='CODEX RECOMMENDATION — NOT FOUNDER APPROVED','proposal classification must remain explicit');pass(truth.ndvi.demo.live_red_nir_processing===false,'demo must not claim live Red/NIR processing');
const activeRoots=[resolve(root,'apps/web/src'),resolve(root,'apps/api/src'),resolve(root,'packages/configuration/src'),resolve(root,'data/product-names.json'),resolve(workspace,'docs/investor-meeting-new-york-2026/web/index.html'),resolve(workspace,'docs/investor-meeting-new-york-2026/web/js/app.js'),resolve(workspace,'docs/investor-meeting-new-york-2026/web/data/use-of-funds.js')],files=[];
const collect=async path=>{const info=await stat(path);if(info.isFile()){files.push(path);return}for(const entry of await readdir(path,{withFileTypes:true})){if(entry.name==='dist'||entry.name==='node_modules')continue;const child=resolve(path,entry.name);if(entry.isDirectory())await collect(child);else if(['.ts','.tsx','.js','.json','.html'].includes(extname(child)))files.push(child)}};for(const path of activeRoots)await collect(path);
const forbidden=[[/Wall[ -]?E/gi,'legacy rover name'],[/DJI Neo/gi,'unapproved drone model'],[/Matrice 350/gi,'unapproved drone model'],[/Mavic 3 Enterprise/gi,'unapproved drone model'],[/(?<![€\d.])\b(?:4|5)\s+m\b/gi,'unapproved Sentinel dimension'],[/\b2[.,]?5\s*M\b|\b2[.,]?500[.,]?000\b|\b2500000\b/gi,'legacy valuation'],[/16[.,]67\s*%/gi,'legacy dilution'],[/500\s*k\s*EBITDA\s*2028/gi,'legacy EBITDA wording']];
for(const file of files){const text=await readFile(file,'utf8');for(const[pattern,label]of forbidden){pattern.lastIndex=0;if(pattern.test(text))failures.push(`${label} in active surface: ${relative(workspace,file)}`)}}
const brandText=await readFile(resolve(root,'packages/configuration/src/index.ts'),'utf8');pass(brandText.includes('roverProductName:truth.terminology.rover'),'brand must consume canonical rover terminology');const investorHtml=await readFile(resolve(workspace,'docs/investor-meeting-new-york-2026/web/index.html'),'utf8');pass(investorHtml.includes('ROVER_001'),'Investor Experience must use ROVER_001');pass(investorHtml.includes('ROUND CONFIGURATION</span><strong>UNDER FINAL REVIEW'),'Investor round must remain under final review');pass(!investorHtml.includes('fundraising-scenarios.json')&&!investorHtml.includes('assumptions.json'),'Investor HTML must not load quarantined financial files');
const order=['opportunity','thesis','system','sentinel','rover','mission','platform','data','evidence','why-now','why-us','business','plan','funds','round','next','closing'];let previous=-1;for(const id of order){const index=investorHtml.indexOf(`id="${id}"`);pass(index>previous,`Investor narrative order invalid at ${id}`);previous=index}
for(const name of['fundraising-scenarios.json','assumptions.json']){const data=JSON.parse(await readFile(resolve(workspace,'docs/investor-meeting-new-york-2026/web/data',name),'utf8'));pass(data.active===false&&data.classification==='HISTORICAL',`${name} must be quarantined as inactive HISTORICAL`)}
if(failures.length){console.error('TRUTH CHECK FAILED');for(const failure of failures)console.error(`✗ ${failure}`);process.exit(1)}console.log(`TRUTH CHECK PASSED · ${files.length} active files checked · canonical ${truth.as_of}`);console.log('Round terms null · legacy claims quarantined · Investor and demo terminology synchronized');
